Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Photo Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "b419ae06-7d63-478e-aac4-5fb2cefa73bc", "8ccc996a-a9b0-4379-a1ea-c608f0d9c8b6", "Child Extension")> _
Partial Public Class [ChildPhotoEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _photoyearcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _photounusable As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _profilephotoyearcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _photoyearcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _photounusable = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _profilephotoyearcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("b419ae06-7d63-478e-aac4-5fb2cefa73bc")
        MyBase.DataFormInstanceId = New Guid("8ccc996a-a9b0-4379-a1ea-c608f0d9c8b6")
        MyBase.RecordType = "Child Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildPhotoEditDataForm.html"

        '
        '_photoyearcodeid
        '
        _photoyearcodeid.Name = "PHOTOYEARCODEID"
        _photoyearcodeid.Caption = "Photo year"
        _photoyearcodeid.Required = True
        _photoyearcodeid.CodeTableName = "USR_CHILDPHOTOYEARCODE"
        Me.Fields.Add(_photoyearcodeid)
        '
        '_photounusable
        '
        _photounusable.Name = "PHOTOUNUSABLE"
        _photounusable.Caption = "Photo unusable"
        _photounusable.Required = True
        Me.Fields.Add(_photounusable)
        '
        '_profilephotoyearcodeid
        '
        _profilephotoyearcodeid.Name = "PROFILEPHOTOYEARCODEID"
        _profilephotoyearcodeid.Caption = "Profile photo year"
        _profilephotoyearcodeid.Required = True
        _profilephotoyearcodeid.CodeTableName = "USR_CHILDPHOTOYEARCODE"
        Me.Fields.Add(_profilephotoyearcodeid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Photo year
    ''' </summary>
    <System.ComponentModel.Description("Photo year")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PHOTOYEARCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _photoyearcodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Photo unusable
    ''' </summary>
    <System.ComponentModel.Description("Photo unusable")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PHOTOUNUSABLE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _photounusable
        End Get
    End Property
    
    ''' <summary>
    ''' Profile photo year
    ''' </summary>
    <System.ComponentModel.Description("Profile photo year")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PROFILEPHOTOYEARCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _profilephotoyearcodeid
        End Get
    End Property
    
End Class
