Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Photo View Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "7a99dc37-1cbc-479c-a67b-15499522f9b5", "8c6d4f1e-4734-4971-b73c-361b863d6e43", "Child Extension")> _
Partial Public Class [ChildPhotoViewDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _photoyear As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _photousable As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _profilephotoyear As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _photoyear = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _photousable = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _profilephotoyear = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("7a99dc37-1cbc-479c-a67b-15499522f9b5")
        MyBase.DataFormInstanceId = New Guid("8c6d4f1e-4734-4971-b73c-361b863d6e43")
        MyBase.RecordType = "Child Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildPhotoViewDataForm.html"

        '
        '_photoyear
        '
        _photoyear.Name = "PHOTOYEAR"
        _photoyear.Caption = "Photo year"
        _photoyear.Required = True
        _photoyear.DBReadOnly = True
        _photoyear.MaxLength = 5
        Me.Fields.Add(_photoyear)
        '
        '_photousable
        '
        _photousable.Name = "PHOTOUSABLE"
        _photousable.Caption = "Photo usable"
        _photousable.DBReadOnly = True
        Me.Fields.Add(_photousable)
        '
        '_profilephotoyear
        '
        _profilephotoyear.Name = "PROFILEPHOTOYEAR"
        _profilephotoyear.Caption = "Profile photo year"
        _profilephotoyear.Required = True
        _profilephotoyear.DBReadOnly = True
        _profilephotoyear.MaxLength = 5
        Me.Fields.Add(_profilephotoyear)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Photo year
    ''' </summary>
    <System.ComponentModel.Description("Photo year")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PHOTOYEAR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _photoyear
        End Get
    End Property
    
    ''' <summary>
    ''' Photo usable
    ''' </summary>
    <System.ComponentModel.Description("Photo usable")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PHOTOUSABLE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _photousable
        End Get
    End Property
    
    ''' <summary>
    ''' Profile photo year
    ''' </summary>
    <System.ComponentModel.Description("Profile photo year")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PROFILEPHOTOYEAR]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _profilephotoyear
        End Get
    End Property
    
End Class
