Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Extension Table Add Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "06465927-9d7c-4e8a-8b8e-0defd8cc90ae", "199882b0-1b47-4af7-b1f6-186f88e5c343", "Child Extension Table")> _
Partial Public Class [ChildExtensionTableAddFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sponsorshipopportunitychildid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _siblingsid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _birthdateaccuracycodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _currentprogramcompletiondate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _childnamesuffixcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _childage As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _childliveswithcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _fatherworksascodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _fatherworksasother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _motherworksascodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _motherworksasother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverrelationcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _caregiverrelationother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverworksascodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _caregiverworksasother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverreasoncodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _reasonforcaregiverother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _numberofsisters As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _numberofbrothers As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _housingwallwood As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _housingwallmud As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _housingwallbamboo As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _housingwallblock As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _housingwallother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _roofingtin As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _roofinggrassleaves As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _roofingwood As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _roofingtile As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _roofingother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _watersourceindoor As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _watersourcecommunitytap As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _watersourceboreholewell As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _watersourceriver As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _watersourceother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _cookingsourcewoodfire As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _cookingsourceelectricstove As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _cookingsourcegasstove As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _cookingsourceother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _lightsourceelectricity As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _lightsourceoillamp As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _lightsourcegenerator As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _lightsourcenone As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _lightsourceother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _areadescription As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _myfavoritethingtodo As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _wheniplaywithfriendswe As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _whenathomeihelpoutby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _whenitalktogodiaskhim As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    'Private WithEvents _wheniamatschoolilikelearning As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _somedayi As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _twomostfavoritethings As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _otherthingsthechildenjoys As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childpersonality As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childhealth As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _spiritualdevelopment As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _attendingschool As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _reasonnotattendingschool As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _classlevel As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _favoritesubject As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _vocationalskills As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _additionalchildinformation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _cchenteredby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _cchtempid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _currentphotodate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _photostored As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childprofilestatuscodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _childprofileupdatecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _profileupdatenotification As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _addsiblingslabel As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _whoamigroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _spiritualdevelopmentgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _parentalinformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _caregiverinformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _siblinginformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _attendingschoolgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _whoamitab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _whoilivewithtab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _whereilivetab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _aboutmetab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _developmenttab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _additionalinfotab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _addsiblings As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _sponsorshipopportunitychildid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _siblingsid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _birthdateaccuracycodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _currentprogramcompletiondate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _childnamesuffixcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _childage = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _childliveswithcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _fatherworksascodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _fatherworksasother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _motherworksascodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _motherworksasother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverrelationcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _caregiverrelationother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverworksascodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _caregiverworksasother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverreasoncodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _reasonforcaregiverother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _numberofsisters = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _numberofbrothers = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _housingwallwood = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _housingwallmud = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _housingwallbamboo = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _housingwallblock = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _housingwallother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _roofingtin = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _roofinggrassleaves = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _roofingwood = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _roofingtile = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _roofingother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _watersourceindoor = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _watersourcecommunitytap = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _watersourceboreholewell = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _watersourceriver = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _watersourceother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _cookingsourcewoodfire = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _cookingsourceelectricstove = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _cookingsourcegasstove = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _cookingsourceother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _lightsourceelectricity = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _lightsourceoillamp = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _lightsourcegenerator = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _lightsourcenone = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _lightsourceother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _areadescription = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _myfavoritethingtodo = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _wheniplaywithfriendswe = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _whenathomeihelpoutby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _whenitalktogodiaskhim = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        '_wheniamatschoolilikelearning = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _somedayi = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _twomostfavoritethings = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _otherthingsthechildenjoys = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childpersonality = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childhealth = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _spiritualdevelopment = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _attendingschool = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _reasonnotattendingschool = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _classlevel = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _favoritesubject = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _vocationalskills = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _additionalchildinformation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _cchenteredby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _cchtempid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _currentphotodate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _photostored = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childprofilestatuscodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _childprofileupdatecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _profileupdatenotification = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _addsiblingslabel = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _whoamigroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _spiritualdevelopmentgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _parentalinformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _caregiverinformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _siblinginformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _attendingschoolgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _whoamitab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _whoilivewithtab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _whereilivetab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _aboutmetab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _developmenttab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _additionalinfotab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _addsiblings = New Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("06465927-9d7c-4e8a-8b8e-0defd8cc90ae")
        MyBase.DataFormInstanceId = New Guid("199882b0-1b47-4af7-b1f6-186f88e5c343")
        MyBase.RecordType = "Child Extension Table"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildExtensionTableAddForm.html"

        '
        '_sponsorshipopportunitychildid
        '
        _sponsorshipopportunitychildid.Name = "SPONSORSHIPOPPORTUNITYCHILDID"
        _sponsorshipopportunitychildid.Caption = "Sponsorshipopportunitychild"
        _sponsorshipopportunitychildid.Required = True
        _sponsorshipopportunitychildid.Visible = False
        Me.Fields.Add(_sponsorshipopportunitychildid)
        '
        '_siblingsid
        '
        _siblingsid.Name = "SIBLINGSID"
        _siblingsid.Caption = "Siblings"
        Me.Fields.Add(_siblingsid)
        '
        '_birthdateaccuracycodeid
        '
        _birthdateaccuracycodeid.Name = "BIRTHDATEACCURACYCODEID"
        _birthdateaccuracycodeid.Caption = "Birthdate Accuracy"
        _birthdateaccuracycodeid.CodeTableName = "USR_BIRTHDATEACCURACYCODE"
        Me.Fields.Add(_birthdateaccuracycodeid)
        '
        '_programcompletiondate
        '
        _currentprogramcompletiondate.Name = "CURRENTPROGRAMCOMPLETIONDATE"
        _currentprogramcompletiondate.Caption = "Current Program Completion Date"
        Me.Fields.Add(_currentprogramcompletiondate)
        '
        '_childnamesuffixcodeid
        '
        _childnamesuffixcodeid.Name = "CHILDNAMESUFFIXCODEID"
        _childnamesuffixcodeid.Caption = "Child Name Suffix"
        _childnamesuffixcodeid.CodeTableName = "USR_CHILDNAMESUFFIXCODE"
        Me.Fields.Add(_childnamesuffixcodeid)
        '
        '_childage
        '
        _childage.Name = "CHILDAGE"
        _childage.Caption = "Child Age"
        _childage.Visible = False
        Me.Fields.Add(_childage)
        '
        '_childliveswithcodeid
        '
        _childliveswithcodeid.Name = "CHILDLIVESWITHCODEID"
        _childliveswithcodeid.Caption = "Child Lives With"
        _childliveswithcodeid.CodeTableName = "USR_CHILDLIVESWITHCODE"
        Me.Fields.Add(_childliveswithcodeid)
        '
        '_fatherworksascodeid
        '
        _fatherworksascodeid.Name = "FATHERWORKSASCODEID"
        _fatherworksascodeid.Caption = "Father Works As"
        _fatherworksascodeid.Required = True
        _fatherworksascodeid.CodeTableName = "USR_FATHERWORKSASCODE"
        Me.Fields.Add(_fatherworksascodeid)
        '
        '_fatherworksasother
        '
        _fatherworksasother.Name = "FATHERWORKSASOTHER"
        _fatherworksasother.Caption = "Father Works as Other"
        _fatherworksasother.MaxLength = 50
        Me.Fields.Add(_fatherworksasother)
        '
        '_motherworksascodeid
        '
        _motherworksascodeid.Name = "MOTHERWORKSASCODEID"
        _motherworksascodeid.Caption = "Mother Works As"
        _motherworksascodeid.Required = True
        _motherworksascodeid.CodeTableName = "USR_MOTHERWORKSASCODE"
        Me.Fields.Add(_motherworksascodeid)
        '
        '_motherworksasother
        '
        _motherworksasother.Name = "MOTHERWORKSASOTHER"
        _motherworksasother.Caption = "Mother Works as Other"
        _motherworksasother.MaxLength = 50
        Me.Fields.Add(_motherworksasother)
        '
        '_caregiverrelationcodeid
        '
        _caregiverrelationcodeid.Name = "CAREGIVERRELATIONCODEID"
        _caregiverrelationcodeid.Caption = "Caregiver Relation"
        _caregiverrelationcodeid.CodeTableName = "USR_CAREGIVERRELATIONCODE"
        Me.Fields.Add(_caregiverrelationcodeid)
        '
        '_caregiverrelationother
        '
        _caregiverrelationother.Name = "CAREGIVERRELATIONOTHER"
        _caregiverrelationother.Caption = "Caregiver Relation Other"
        _caregiverrelationother.MaxLength = 50
        Me.Fields.Add(_caregiverrelationother)
        '
        '_caregiverworksascodeid
        '
        _caregiverworksascodeid.Name = "CAREGIVERWORKSASCODEID"
        _caregiverworksascodeid.Caption = "Caregiver Works As"
        _caregiverworksascodeid.CodeTableName = "USR_CAREGIVERWORKSASCODE"
        Me.Fields.Add(_caregiverworksascodeid)
        '
        '_caregiverworksasother
        '
        _caregiverworksasother.Name = "CAREGIVERWORKSASOTHER"
        _caregiverworksasother.Caption = "Caregiver Works as Other"
        _caregiverworksasother.MaxLength = 50
        Me.Fields.Add(_caregiverworksasother)
        '
        '_caregiverreasoncodeid
        '
        _caregiverreasoncodeid.Name = "CAREGIVERREASONCODEID"
        _caregiverreasoncodeid.Caption = "Caregiver Reason"
        _caregiverreasoncodeid.CodeTableName = "USR_CAREGIVERREASONCODE"
        Me.Fields.Add(_caregiverreasoncodeid)
        '
        '_reasonforcaregiverother
        '
        _reasonforcaregiverother.Name = "REASONFORCAREGIVEROTHER"
        _reasonforcaregiverother.Caption = "Reason for Caregiver Other"
        _reasonforcaregiverother.MaxLength = 50
        Me.Fields.Add(_reasonforcaregiverother)
        '
        '_numberofsisters
        '
        _numberofsisters.Name = "NUMBEROFSISTERS"
        _numberofsisters.Caption = "Number of sisters"
        Me.Fields.Add(_numberofsisters)
        '
        '_numberofbrothers
        '
        _numberofbrothers.Name = "NUMBEROFBROTHERS"
        _numberofbrothers.Caption = "Number of brothers"
        Me.Fields.Add(_numberofbrothers)
        '
        '_housingwallwood
        '
        _housingwallwood.Name = "HOUSINGWALLWOOD"
        _housingwallwood.Caption = "Wood"
        Me.Fields.Add(_housingwallwood)
        '
        '_housingwallmud
        '
        _housingwallmud.Name = "HOUSINGWALLMUD"
        _housingwallmud.Caption = "Mud"
        Me.Fields.Add(_housingwallmud)
        '
        '_housingwallbamboo
        '
        _housingwallbamboo.Name = "HOUSINGWALLBAMBOO"
        _housingwallbamboo.Caption = "Bamboo"
        Me.Fields.Add(_housingwallbamboo)
        '
        '_housingwallblock
        '
        _housingwallblock.Name = "HOUSINGWALLBLOCK"
        _housingwallblock.Caption = "Block"
        Me.Fields.Add(_housingwallblock)
        '
        '_housingwallother
        '
        _housingwallother.Name = "HOUSINGWALLOTHER"
        _housingwallother.Caption = "Housing Wall Other"
        _housingwallother.MaxLength = 50
        Me.Fields.Add(_housingwallother)
        '
        '_roofingtin
        '
        _roofingtin.Name = "ROOFINGTIN"
        _roofingtin.Caption = "Tin"
        Me.Fields.Add(_roofingtin)
        '
        '_roofinggrassleaves
        '
        _roofinggrassleaves.Name = "ROOFINGGRASSLEAVES"
        _roofinggrassleaves.Caption = "Grass/leaves"
        Me.Fields.Add(_roofinggrassleaves)
        '
        '_roofingwood
        '
        _roofingwood.Name = "ROOFINGWOOD"
        _roofingwood.Caption = "Roofing Wood"
        Me.Fields.Add(_roofingwood)
        '
        '_roofingtile
        '
        _roofingtile.Name = "ROOFINGTILE"
        _roofingtile.Caption = "Tile"
        Me.Fields.Add(_roofingtile)
        '
        '_roofingother
        '
        _roofingother.Name = "ROOFINGOTHER"
        _roofingother.Caption = "Roofing Other"
        _roofingother.MaxLength = 50
        Me.Fields.Add(_roofingother)
        '
        '_watersourceindoor
        '
        _watersourceindoor.Name = "WATERSOURCEINDOOR"
        _watersourceindoor.Caption = "Indoor"
        Me.Fields.Add(_watersourceindoor)
        '
        '_watersourcecommunitytap
        '
        _watersourcecommunitytap.Name = "WATERSOURCECOMMUNITYTAP"
        _watersourcecommunitytap.Caption = "Community Tap"
        Me.Fields.Add(_watersourcecommunitytap)
        '
        '_watersourceboreholewell
        '
        _watersourceboreholewell.Name = "WATERSOURCEBOREHOLEWELL"
        _watersourceboreholewell.Caption = "Borehole/Well"
        Me.Fields.Add(_watersourceboreholewell)
        '
        '_watersourceriver
        '
        _watersourceriver.Name = "WATERSOURCERIVER"
        _watersourceriver.Caption = "River"
        Me.Fields.Add(_watersourceriver)
        '
        '_watersourceother
        '
        _watersourceother.Name = "WATERSOURCEOTHER"
        _watersourceother.Caption = "Water Source Other"
        _watersourceother.MaxLength = 50
        Me.Fields.Add(_watersourceother)
        '
        '_cookingsourcewoodfire
        '
        _cookingsourcewoodfire.Name = "COOKINGSOURCEWOODFIRE"
        _cookingsourcewoodfire.Caption = "Wood Fire"
        Me.Fields.Add(_cookingsourcewoodfire)
        '
        '_cookingsourceelectricstove
        '
        _cookingsourceelectricstove.Name = "COOKINGSOURCEELECTRICSTOVE"
        _cookingsourceelectricstove.Caption = "Electric Stove"
        Me.Fields.Add(_cookingsourceelectricstove)
        '
        '_cookingsourcegasstove
        '
        _cookingsourcegasstove.Name = "COOKINGSOURCEGASSTOVE"
        _cookingsourcegasstove.Caption = "Gas Stove"
        Me.Fields.Add(_cookingsourcegasstove)
        '
        '_cookingsourceother
        '
        _cookingsourceother.Name = "COOKINGSOURCEOTHER"
        _cookingsourceother.Caption = "Cooking Source Other"
        _cookingsourceother.MaxLength = 50
        Me.Fields.Add(_cookingsourceother)
        '
        '_lightsourceelectricity
        '
        _lightsourceelectricity.Name = "LIGHTSOURCEELECTRICITY"
        _lightsourceelectricity.Caption = "Electricity"
        Me.Fields.Add(_lightsourceelectricity)
        '
        '_lightsourceoillamp
        '
        _lightsourceoillamp.Name = "LIGHTSOURCEOILLAMP"
        _lightsourceoillamp.Caption = "Oil Lamp"
        Me.Fields.Add(_lightsourceoillamp)
        '
        '_lightsourcegenerator
        '
        _lightsourcegenerator.Name = "LIGHTSOURCEGENERATOR"
        _lightsourcegenerator.Caption = "Generator"
        Me.Fields.Add(_lightsourcegenerator)
        '
        '_lightsourcenone
        '
        _lightsourcenone.Name = "LIGHTSOURCENONE"
        _lightsourcenone.Caption = "None"
        Me.Fields.Add(_lightsourcenone)
        '
        '_lightsourceother
        '
        _lightsourceother.Name = "LIGHTSOURCEOTHER"
        _lightsourceother.Caption = "Light Source Other"
        _lightsourceother.MaxLength = 50
        Me.Fields.Add(_lightsourceother)
        '
        '_areadescription
        '
        _areadescription.Name = "AREADESCRIPTION"
        _areadescription.Caption = "Area Description"
        _areadescription.MaxLength = 1000
        _areadescription.Multiline = True
        Me.Fields.Add(_areadescription)
        '
        '_myfavoritethingtodo
        '
        _myfavoritethingtodo.Name = "MYFAVORITETHINGTODO"
        _myfavoritethingtodo.Caption = "My favoritething to do when I am by myself is"
        _myfavoritethingtodo.MaxLength = 1000
        _myfavoritethingtodo.Multiline = True
        Me.Fields.Add(_myfavoritethingtodo)
        '
        '_wheniplaywithfriendswe
        '
        _wheniplaywithfriendswe.Name = "WHENIPLAYWITHFRIENDSWE"
        _wheniplaywithfriendswe.Caption = "When I play with my friends we"
        _wheniplaywithfriendswe.MaxLength = 1000
        _wheniplaywithfriendswe.Multiline = True
        Me.Fields.Add(_wheniplaywithfriendswe)
        '
        '_whenathomeihelpoutby
        '
        _whenathomeihelpoutby.Name = "WHENATHOMEIHELPOUTBY"
        _whenathomeihelpoutby.Caption = "When at home I help out by"
        _whenathomeihelpoutby.MaxLength = 1000
        _whenathomeihelpoutby.Multiline = True
        Me.Fields.Add(_whenathomeihelpoutby)
        '
        '_whenitalktogodiaskhim
        '
        _whenitalktogodiaskhim.Name = "WHENITALKTOGODIASKHIM"
        _whenitalktogodiaskhim.Caption = "When I talk to God I ask Him"
        _whenitalktogodiaskhim.MaxLength = 1000
        _whenitalktogodiaskhim.Multiline = True
        Me.Fields.Add(_whenitalktogodiaskhim)
        '
        '_wheniamatschoolilikelearning
        '
        '_wheniamatschoolilikelearning.Name = "WHENIAMATSCHOOLILIKELEARNING"
        '_wheniamatschoolilikelearning.Caption = "When I am at school I like..."
        '_wheniamatschoolilikelearning.Visible = False
        '_wheniamatschoolilikelearning.MaxLength = 1000
        '_wheniamatschoolilikelearning.Multiline = True
        'Me.Fields.Add(_wheniamatschoolilikelearning)
        '
        '_somedayi
        '
        _somedayi.Name = "SOMEDAYI"
        _somedayi.Caption = "Someday I..."
        _somedayi.MaxLength = 1000
        _somedayi.Multiline = True
        Me.Fields.Add(_somedayi)
        '
        '_twomostfavoritethings
        '
        _twomostfavoritethings.Name = "TWOMOSTFAVORITETHINGS"
        _twomostfavoritethings.Caption = "Two or more favorite things"
        _twomostfavoritethings.MaxLength = 1000
        _twomostfavoritethings.Multiline = True
        Me.Fields.Add(_twomostfavoritethings)
        '
        '_otherthingsthechildenjoys
        '
        _otherthingsthechildenjoys.Name = "OTHERTHINGSTHECHILDENJOYS"
        _otherthingsthechildenjoys.Caption = "Other things the child enjoys"
        _otherthingsthechildenjoys.MaxLength = 1000
        _otherthingsthechildenjoys.Multiline = True
        Me.Fields.Add(_otherthingsthechildenjoys)
        '
        '_childpersonality
        '
        _childpersonality.Name = "CHILDPERSONALITY"
        _childpersonality.Caption = "Describes the child's personality or qualities that make them unique or special as well as how they interact with and relate to other children"
        _childpersonality.MaxLength = 1000
        _childpersonality.Multiline = True
        Me.Fields.Add(_childpersonality)
        '
        '_childhealth
        '
        _childhealth.Name = "CHILDHEALTH"
        _childhealth.Caption = "Describes the child's current health including any special concerns or conditions"
        _childhealth.MaxLength = 1000
        _childhealth.Multiline = True
        Me.Fields.Add(_childhealth)
        '
        '_spiritualdevelopment
        '
        _spiritualdevelopment.Name = "SPIRITUALDEVELOPMENT"
        _spiritualdevelopment.Caption = "Describes the child's current level of faith, spiritual understanding and Christian activities"
        _spiritualdevelopment.MaxLength = 1000
        _spiritualdevelopment.Multiline = True
        Me.Fields.Add(_spiritualdevelopment)
        '
        '_attendingschool
        '
        _attendingschool.Name = "ATTENDINGSCHOOL"
        _attendingschool.Caption = "Attending School"
        Me.Fields.Add(_attendingschool)
        '
        '_reasonnotattendingschool
        '
        _reasonnotattendingschool.Name = "REASONNOTATTENDINGSCHOOL"
        _reasonnotattendingschool.Caption = "If No, give reason"
        _reasonnotattendingschool.MaxLength = 255
        _reasonnotattendingschool.Multiline = True
        Me.Fields.Add(_reasonnotattendingschool)
        '
        '_classlevel
        '
        _classlevel.Name = "CLASSLEVEL"
        _classlevel.Caption = "Class Level"
        _classlevel.MaxLength = 20
        Me.Fields.Add(_classlevel)
        '
        '_favoritesubject
        '
        _favoritesubject.Name = "FAVORITESUBJECT"
        _favoritesubject.Caption = "Favorite subject or learning activity and why"
        _favoritesubject.MaxLength = 1000
        _favoritesubject.Multiline = True
        Me.Fields.Add(_favoritesubject)
        '
        '_vocationalskills
        '
        _vocationalskills.Name = "VOCATIONALSKILLS"
        _vocationalskills.Caption = "Vocational or life skills..."
        _vocationalskills.MaxLength = 1000
        _vocationalskills.Multiline = True
        Me.Fields.Add(_vocationalskills)
        '
        '_additionalchildinformation
        '
        _additionalchildinformation.Name = "ADDITIONALCHILDINFORMATION"
        _additionalchildinformation.Caption = "Additional Child Information"
        Me.Fields.Add(_additionalchildinformation)
        '
        '_cchenteredby
        '
        _cchenteredby.Name = "CCHENTEREDBY"
        _cchenteredby.Caption = "CCH Entered By"
        _cchenteredby.MaxLength = 100
        Me.Fields.Add(_cchenteredby)
        '
        '_cchtempid
        '
        _cchtempid.Name = "CCHTEMPID"
        _cchtempid.Caption = "Ch Tempid"
        _cchtempid.MaxLength = 250
        _cchtempid.Multiline = True
        Me.Fields.Add(_cchtempid)
        '
        '_currentphotodate
        '
        _currentphotodate.Name = "CURRENTPHOTODATE"
        _currentphotodate.Caption = "Current Photo Date"
        _currentphotodate.Required = True
        Me.Fields.Add(_currentphotodate)
        '
        '_photostored
        '
        _photostored.Name = "PHOTOSTORED"
        _photostored.Caption = "Photo Stored"
        Me.Fields.Add(_photostored)
        '
        '_childprofilestatuscodeid
        '
        _childprofilestatuscodeid.Name = "CHILDPROFILESTATUSCODEID"
        _childprofilestatuscodeid.Caption = "Child Profile Status"
        _childprofilestatuscodeid.Required = True
        _childprofilestatuscodeid.CodeTableName = "USR_CHILDPROFILESTATUSCODE"
        Me.Fields.Add(_childprofilestatuscodeid)
        '
        '_childprofileupdatecodeid
        '
        _childprofileupdatecodeid.Name = "CHILDPROFILEUPDATECODEID"
        _childprofileupdatecodeid.Caption = "Child Profile Update"
        _childprofileupdatecodeid.CodeTableName = "USR_CHILDPROFILEUPDATECODE"
        Me.Fields.Add(_childprofileupdatecodeid)
        '
        '_profileupdatenotification
        '
        _profileupdatenotification.Name = "PROFILEUPDATENOTIFICATION"
        _profileupdatenotification.Caption = "Profile Update Notification"
        Me.Fields.Add(_profileupdatenotification)
        '
        '_addsiblingslabel
        '
        _addsiblingslabel.Name = "ADDSIBLINGSLABEL"
        _addsiblingslabel.Caption = "Add Siblings"
        _addsiblingslabel.DBReadOnly = True
        Me.Fields.Add(_addsiblingslabel)
        '
        '_whoamigroup
        '
        _whoamigroup.Name = "WHOAMI_GROUP"
        _whoamigroup.Caption = "Who Am I"
        _whoamigroup.Fields.Add("FIRSTNAME")
        _whoamigroup.Fields.Add("MIDDLENAME")
        _whoamigroup.Fields.Add("LASTNAME")
        _whoamigroup.Fields.Add("CHILDNAMESUFFIXCODEID")
        _whoamigroup.Fields.Add("GENDER")
        _whoamigroup.Fields.Add("AGE")
        _whoamigroup.Fields.Add("BIRTHDATEACCURACYCODEID")
        _whoamigroup.Fields.Add("BIRTHDATE")
        Me.Fields.Add(_whoamigroup)
        '
        '_spiritualdevelopmentgroup
        '
        _spiritualdevelopmentgroup.Name = "SPIRITUAL_DEVELOPMENT_GROUP"
        _spiritualdevelopmentgroup.Caption = "Spritual Development"
        _spiritualdevelopmentgroup.Fields.Add("SPIRITUALDEVELOPMENT")
        Me.Fields.Add(_spiritualdevelopmentgroup)
        '
        '_parentalinformationgroup
        '
        _parentalinformationgroup.Name = "PARENTAL_INFORMATION_GROUP"
        _parentalinformationgroup.Caption = "Parental Information"
        _parentalinformationgroup.Fields.Add("CHILDLIVESWITHCODEID")
        _parentalinformationgroup.Fields.Add("FATHERWORKSASCODEID")
        _parentalinformationgroup.Fields.Add("FATHERWORKSASOTHER")
        _parentalinformationgroup.Fields.Add("MOTHERWORKSASCODEID")
        _parentalinformationgroup.Fields.Add("MOTHERWORKSASOTHER")
        Me.Fields.Add(_parentalinformationgroup)
        '
        '_caregiverinformationgroup
        '
        _caregiverinformationgroup.Name = "CAREGIVER_INFORMATION_GROUP"
        _caregiverinformationgroup.Caption = "Caregiver Information"
        _caregiverinformationgroup.Fields.Add("CAREGIVERRELATIONCODEID")
        _caregiverinformationgroup.Fields.Add("CAREGIVERRELATIONOTHER")
        _caregiverinformationgroup.Fields.Add("CAREGIVERWORKSASCODEID")
        _caregiverinformationgroup.Fields.Add("CAREGIVERWORKSASOTHER")
        _caregiverinformationgroup.Fields.Add("CAREGIVERREASONCODEID")
        _caregiverinformationgroup.Fields.Add("REASONFORCAREGIVEROTHER")
        Me.Fields.Add(_caregiverinformationgroup)
        '
        '_siblinginformationgroup
        '
        _siblinginformationgroup.Name = "SIBLING_INFORMATION_GROUP"
        _siblinginformationgroup.Caption = "Sibling Information"
        _siblinginformationgroup.Fields.Add("NUMBEROFSISTERS")
        _siblinginformationgroup.Fields.Add("NUMBEROFBROTHERS")
        Me.Fields.Add(_siblinginformationgroup)
        '
        '_attendingschoolgroup
        '
        _attendingschoolgroup.Name = "ATTENDING_SCHOOL_GROUP"
        _attendingschoolgroup.Caption = "Attending School"
        _attendingschoolgroup.Fields.Add("ATTENDINGSCHOOL")
        _attendingschoolgroup.Fields.Add("REASONNOTATTENDINGSCHOOL")
        _attendingschoolgroup.Fields.Add("CLASSLEVEL")
        _attendingschoolgroup.Fields.Add("FAVORITESUBJECT")
        _attendingschoolgroup.Fields.Add("VOCATIONALSKILLS")
        Me.Fields.Add(_attendingschoolgroup)
        '
        '_whoamitab
        '
        _whoamitab.Name = "WHOAMI_TAB"
        _whoamitab.Caption = "Who Am I"
        Me.Fields.Add(_whoamitab)
        '
        '_whoilivewithtab
        '
        _whoilivewithtab.Name = "WHOILIVEWITH_TAB"
        _whoilivewithtab.Caption = "Who I Live With"
        Me.Fields.Add(_whoilivewithtab)
        '
        '_whereilivetab
        '
        _whereilivetab.Name = "WHEREILIVE_TAB"
        _whereilivetab.Caption = "Where I Live"
        Me.Fields.Add(_whereilivetab)
        '
        '_aboutmetab
        '
        _aboutmetab.Name = "ABOUTME_TAB"
        _aboutmetab.Caption = "About Me"
        Me.Fields.Add(_aboutmetab)
        '
        '_developmenttab
        '
        _developmenttab.Name = "DEVELOPMENT_TAB"
        _developmenttab.Caption = "Development"
        Me.Fields.Add(_developmenttab)
        '
        '_additionalinfotab
        '
        _additionalinfotab.Name = "ADDITIONALINFO_TAB"
        _additionalinfotab.Caption = "Additional Info"
        Me.Fields.Add(_additionalinfotab)
        '
        '_addsiblings
        '
        _addsiblings.Name = "ADDSIBLINGS"
        _addsiblings.Caption = "+"
        _addsiblings.Description = "Add Siblings"
        _addsiblings.DataFormInstanceId = New Guid("173d9386-e5d8-4628-b756-2beac170f91f")
        Me.Actions.Add(_addsiblings)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Sponsorshipopportunitychild
    ''' </summary>
    <System.ComponentModel.Description("Sponsorshipopportunitychild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipopportunitychildid
        End Get
    End Property

    ''' <summary>
    ''' Siblings
    ''' </summary>
    <System.ComponentModel.Description("Siblings")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SIBLINGSID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _siblingsid
        End Get
    End Property

    ''' <summary>
    ''' Birthdate Accuracy
    ''' </summary>
    <System.ComponentModel.Description("Birthdate Accuracy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [BIRTHDATEACCURACYCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _birthdateaccuracycodeid
        End Get
    End Property

    ''' <summary>
    ''' Program Completion Date
    ''' </summary>
    <System.ComponentModel.Description("Current Program Completion Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CURRENTPROGRAMCOMPLETIONDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _currentprogramcompletiondate
        End Get
    End Property

    ''' <summary>
    ''' Child Name Suffix
    ''' </summary>
    <System.ComponentModel.Description("Child Name Suffix")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDNAMESUFFIXCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _childnamesuffixcodeid
        End Get
    End Property

    ''' <summary>
    ''' Child Age
    ''' </summary>
    <System.ComponentModel.Description("Child Age")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _childage
        End Get
    End Property

    ''' <summary>
    ''' Child Lives With
    ''' </summary>
    <System.ComponentModel.Description("Child Lives With")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDLIVESWITHCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _childliveswithcodeid
        End Get
    End Property

    ''' <summary>
    ''' Father Works As
    ''' </summary>
    <System.ComponentModel.Description("Father Works As")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FATHERWORKSASCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _fatherworksascodeid
        End Get
    End Property

    ''' <summary>
    ''' Father Works as Other
    ''' </summary>
    <System.ComponentModel.Description("Father Works as Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FATHERWORKSASOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _fatherworksasother
        End Get
    End Property

    ''' <summary>
    ''' Mother Works As
    ''' </summary>
    <System.ComponentModel.Description("Mother Works As")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MOTHERWORKSASCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _motherworksascodeid
        End Get
    End Property

    ''' <summary>
    ''' Mother Works as Other
    ''' </summary>
    <System.ComponentModel.Description("Mother Works as Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MOTHERWORKSASOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _motherworksasother
        End Get
    End Property

    ''' <summary>
    ''' Caregiver Relation
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Relation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERRELATIONCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _caregiverrelationcodeid
        End Get
    End Property

    ''' <summary>
    ''' Caregiver Relation Other
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Relation Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERRELATIONOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverrelationother
        End Get
    End Property

    ''' <summary>
    ''' Caregiver Works As
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Works As")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERWORKSASCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _caregiverworksascodeid
        End Get
    End Property

    ''' <summary>
    ''' Caregiver Works as Other
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Works as Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERWORKSASOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverworksasother
        End Get
    End Property

    ''' <summary>
    ''' Caregiver Reason
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERREASONCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _caregiverreasoncodeid
        End Get
    End Property

    ''' <summary>
    ''' Reason for Caregiver Other
    ''' </summary>
    <System.ComponentModel.Description("Reason for Caregiver Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [REASONFORCAREGIVEROTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _reasonforcaregiverother
        End Get
    End Property

    ''' <summary>
    ''' Number of sisters
    ''' </summary>
    <System.ComponentModel.Description("Number of sisters")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NUMBEROFSISTERS]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _numberofsisters
        End Get
    End Property

    ''' <summary>
    ''' Number of brothers
    ''' </summary>
    <System.ComponentModel.Description("Number of brothers")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NUMBEROFBROTHERS]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _numberofbrothers
        End Get
    End Property

    ''' <summary>
    ''' Wood
    ''' </summary>
    <System.ComponentModel.Description("Wood")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HOUSINGWALLWOOD]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _housingwallwood
        End Get
    End Property

    ''' <summary>
    ''' Mud
    ''' </summary>
    <System.ComponentModel.Description("Mud")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HOUSINGWALLMUD]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _housingwallmud
        End Get
    End Property

    ''' <summary>
    ''' Bamboo
    ''' </summary>
    <System.ComponentModel.Description("Bamboo")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HOUSINGWALLBAMBOO]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _housingwallbamboo
        End Get
    End Property

    ''' <summary>
    ''' Block
    ''' </summary>
    <System.ComponentModel.Description("Block")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HOUSINGWALLBLOCK]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _housingwallblock
        End Get
    End Property

    ''' <summary>
    ''' Housing Wall Other
    ''' </summary>
    <System.ComponentModel.Description("Housing Wall Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HOUSINGWALLOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _housingwallother
        End Get
    End Property

    ''' <summary>
    ''' Tin
    ''' </summary>
    <System.ComponentModel.Description("Tin")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ROOFINGTIN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _roofingtin
        End Get
    End Property

    ''' <summary>
    ''' Grass/leaves
    ''' </summary>
    <System.ComponentModel.Description("Grass/leaves")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ROOFINGGRASSLEAVES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _roofinggrassleaves
        End Get
    End Property

    ''' <summary>
    ''' Roofing Wood
    ''' </summary>
    <System.ComponentModel.Description("Roofing Wood")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ROOFINGWOOD]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _roofingwood
        End Get
    End Property

    ''' <summary>
    ''' Tile
    ''' </summary>
    <System.ComponentModel.Description("Tile")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ROOFINGTILE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _roofingtile
        End Get
    End Property

    ''' <summary>
    ''' Roofing Other
    ''' </summary>
    <System.ComponentModel.Description("Roofing Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ROOFINGOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _roofingother
        End Get
    End Property

    ''' <summary>
    ''' Indoor
    ''' </summary>
    <System.ComponentModel.Description("Indoor")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WATERSOURCEINDOOR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _watersourceindoor
        End Get
    End Property

    ''' <summary>
    ''' Community Tap
    ''' </summary>
    <System.ComponentModel.Description("Community Tap")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WATERSOURCECOMMUNITYTAP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _watersourcecommunitytap
        End Get
    End Property

    ''' <summary>
    ''' Borehole/Well
    ''' </summary>
    <System.ComponentModel.Description("Borehole/Well")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WATERSOURCEBOREHOLEWELL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _watersourceboreholewell
        End Get
    End Property

    ''' <summary>
    ''' River
    ''' </summary>
    <System.ComponentModel.Description("River")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WATERSOURCERIVER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _watersourceriver
        End Get
    End Property

    ''' <summary>
    ''' Water Source Other
    ''' </summary>
    <System.ComponentModel.Description("Water Source Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WATERSOURCEOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _watersourceother
        End Get
    End Property

    ''' <summary>
    ''' Wood Fire
    ''' </summary>
    <System.ComponentModel.Description("Wood Fire")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COOKINGSOURCEWOODFIRE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _cookingsourcewoodfire
        End Get
    End Property

    ''' <summary>
    ''' Electric Stove
    ''' </summary>
    <System.ComponentModel.Description("Electric Stove")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COOKINGSOURCEELECTRICSTOVE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _cookingsourceelectricstove
        End Get
    End Property

    ''' <summary>
    ''' Gas Stove
    ''' </summary>
    <System.ComponentModel.Description("Gas Stove")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COOKINGSOURCEGASSTOVE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _cookingsourcegasstove
        End Get
    End Property

    ''' <summary>
    ''' Cooking Source Other
    ''' </summary>
    <System.ComponentModel.Description("Cooking Source Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COOKINGSOURCEOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _cookingsourceother
        End Get
    End Property

    ''' <summary>
    ''' Electricity
    ''' </summary>
    <System.ComponentModel.Description("Electricity")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LIGHTSOURCEELECTRICITY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _lightsourceelectricity
        End Get
    End Property

    ''' <summary>
    ''' Oil Lamp
    ''' </summary>
    <System.ComponentModel.Description("Oil Lamp")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LIGHTSOURCEOILLAMP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _lightsourceoillamp
        End Get
    End Property

    ''' <summary>
    ''' Generator
    ''' </summary>
    <System.ComponentModel.Description("Generator")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LIGHTSOURCEGENERATOR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _lightsourcegenerator
        End Get
    End Property

    ''' <summary>
    ''' None
    ''' </summary>
    <System.ComponentModel.Description("None")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LIGHTSOURCENONE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _lightsourcenone
        End Get
    End Property

    ''' <summary>
    ''' Light Source Other
    ''' </summary>
    <System.ComponentModel.Description("Light Source Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LIGHTSOURCEOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _lightsourceother
        End Get
    End Property

    ''' <summary>
    ''' Area Description
    ''' </summary>
    <System.ComponentModel.Description("Area Description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [AREADESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _areadescription
        End Get
    End Property

    ''' <summary>
    ''' My favoritething to do when I am by myself is
    ''' </summary>
    <System.ComponentModel.Description("My favoritething to do when I am by myself is")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MYFAVORITETHINGTODO]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _myfavoritethingtodo
        End Get
    End Property

    ''' <summary>
    ''' When I play with my friends we
    ''' </summary>
    <System.ComponentModel.Description("When I play with my friends we")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHENIPLAYWITHFRIENDSWE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _wheniplaywithfriendswe
        End Get
    End Property

    ''' <summary>
    ''' When at home I help out by
    ''' </summary>
    <System.ComponentModel.Description("When at home I help out by")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHENATHOMEIHELPOUTBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _whenathomeihelpoutby
        End Get
    End Property

    ''' <summary>
    ''' When I talk to God I ask Him
    ''' </summary>
    <System.ComponentModel.Description("When I talk to God I ask Him")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHENITALKTOGODIASKHIM]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _whenitalktogodiaskhim
        End Get
    End Property

    ''' <summary>
    ''' When I am at school I like...
    ''' </summary>
    '<System.ComponentModel.Description("When I am at school I like...")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [WHENIAMATSCHOOLILIKELEARNING]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    '    Get
    '        Return _wheniamatschoolilikelearning
    '    End Get
    'End Property

    ''' <summary>
    ''' Someday I...
    ''' </summary>
    <System.ComponentModel.Description("Someday I...")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOMEDAYI]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _somedayi
        End Get
    End Property

    ''' <summary>
    ''' Two or more favorite things
    ''' </summary>
    <System.ComponentModel.Description("Two or more favorite things")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [TWOMOSTFAVORITETHINGS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _twomostfavoritethings
        End Get
    End Property

    ''' <summary>
    ''' Other things the child enjoys
    ''' </summary>
    <System.ComponentModel.Description("Other things the child enjoys")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [OTHERTHINGSTHECHILDENJOYS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _otherthingsthechildenjoys
        End Get
    End Property

    ''' <summary>
    ''' Describe child's personality and how they interact
    ''' </summary>
    <System.ComponentModel.Description("Describes the child's personality or qualities that make them unique or special as well as how they interact with and relate to other children")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDPERSONALITY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childpersonality
        End Get
    End Property

    ''' <summary>
    ''' Child's current health...
    ''' </summary>
    <System.ComponentModel.Description("Describes the child's current health including any special concerns or conditions")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDHEALTH]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childhealth
        End Get
    End Property

    ''' <summary>
    ''' Child's current level of faith...
    ''' </summary>
    <System.ComponentModel.Description("Describes the child's current level of faith, spiritual understanding and Christian activities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPIRITUALDEVELOPMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _spiritualdevelopment
        End Get
    End Property

    ''' <summary>
    ''' Attending School
    ''' </summary>
    <System.ComponentModel.Description("Attending School")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ATTENDINGSCHOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _attendingschool
        End Get
    End Property

    ''' <summary>
    ''' If No, give reason
    ''' </summary>
    <System.ComponentModel.Description("If No, give reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [REASONNOTATTENDINGSCHOOL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _reasonnotattendingschool
        End Get
    End Property

    ''' <summary>
    ''' Class Level
    ''' </summary>
    <System.ComponentModel.Description("Class Level")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CLASSLEVEL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _classlevel
        End Get
    End Property

    ''' <summary>
    ''' Favorite subject or learning activity and why
    ''' </summary>
    <System.ComponentModel.Description("Favorite subject or learning activity and why")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FAVORITESUBJECT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _favoritesubject
        End Get
    End Property

    ''' <summary>
    ''' Vocational or life skills...
    ''' </summary>
    <System.ComponentModel.Description("Vocational or life skills...")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [VOCATIONALSKILLS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _vocationalskills
        End Get
    End Property

    ''' <summary>
    ''' Additional Child Information
    ''' </summary>
    <System.ComponentModel.Description("Additional Child Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADDITIONALCHILDINFORMATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _additionalchildinformation
        End Get
    End Property

    ''' <summary>
    ''' CCH Entered By
    ''' </summary>
    <System.ComponentModel.Description("CCH Entered By")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CCHENTEREDBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _cchenteredby
        End Get
    End Property

    ''' <summary>
    ''' Ch Tempid
    ''' </summary>
    <System.ComponentModel.Description("CH CCH Tempid")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CCHTEMPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _cchtempid
        End Get
    End Property

    ''' <summary>
    ''' Current Photo Date
    ''' </summary>
    <System.ComponentModel.Description("Current Photo Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CURRENTPHOTODATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _currentphotodate
        End Get
    End Property

    ''' <summary>
    ''' Photo Stored
    ''' </summary>
    <System.ComponentModel.Description("Photo Stored")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PHOTOSTORED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _photostored
        End Get
    End Property
    
    ''' <summary>
    ''' Child Profile Status
    ''' </summary>
    <System.ComponentModel.Description("Child Profile Status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDPROFILESTATUSCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _childprofilestatuscodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Child Profile Update
    ''' </summary>
    <System.ComponentModel.Description("Child Profile Update")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDPROFILEUPDATECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _childprofileupdatecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Profile Update Notification
    ''' </summary>
    <System.ComponentModel.Description("Profile Update Notification")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PROFILEUPDATENOTIFICATION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _profileupdatenotification
        End Get
    End Property
    
    ''' <summary>
    ''' Add Siblings
    ''' </summary>
    <System.ComponentModel.Description("Add Siblings")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADDSIBLINGSLABEL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _addsiblingslabel
        End Get
    End Property
    
    ''' <summary>
    ''' Who Am I
    ''' </summary>
    <System.ComponentModel.Description("Who Am I")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHOAMI_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _whoamigroup
        End Get
    End Property
    
    ''' <summary>
    ''' Spritual Development
    ''' </summary>
    <System.ComponentModel.Description("Spritual Development")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPIRITUAL_DEVELOPMENT_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _spiritualdevelopmentgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Parental Information
    ''' </summary>
    <System.ComponentModel.Description("Parental Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PARENTAL_INFORMATION_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _parentalinformationgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Information
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVER_INFORMATION_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _caregiverinformationgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Sibling Information
    ''' </summary>
    <System.ComponentModel.Description("Sibling Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SIBLING_INFORMATION_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _siblinginformationgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Attending School
    ''' </summary>
    <System.ComponentModel.Description("Attending School")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ATTENDING_SCHOOL_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _attendingschoolgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Who Am I
    ''' </summary>
    <System.ComponentModel.Description("Who Am I")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHOAMI_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _whoamitab
        End Get
    End Property
    
    ''' <summary>
    ''' Who I Live With
    ''' </summary>
    <System.ComponentModel.Description("Who I Live With")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHOILIVEWITH_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _whoilivewithtab
        End Get
    End Property
    
    ''' <summary>
    ''' Where I Live
    ''' </summary>
    <System.ComponentModel.Description("Where I Live")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHEREILIVE_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _whereilivetab
        End Get
    End Property
    
    ''' <summary>
    ''' About Me
    ''' </summary>
    <System.ComponentModel.Description("About Me")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ABOUTME_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _aboutmetab
        End Get
    End Property
    
    ''' <summary>
    ''' Development
    ''' </summary>
    <System.ComponentModel.Description("Development")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEVELOPMENT_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _developmenttab
        End Get
    End Property
    
    ''' <summary>
    ''' Additional Info
    ''' </summary>
    <System.ComponentModel.Description("Additional Info")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADDITIONALINFO_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _additionalinfotab
        End Get
    End Property
    
    ''' <summary>
    ''' Add Siblings
    ''' </summary>
    <System.ComponentModel.Description("Add Siblings")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADDSIBLINGS]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction
        Get
            Return _addsiblings
        End Get
    End Property
    
End Class
