Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildExtension About Me Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "29385eae-7328-4c26-be11-657455d48a09", "55f5b7f0-5207-40c6-ba5a-5907a7721aa7", "Child Extension")> _
Partial Public Class [ChildExtensionAboutMeEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _myfavoritethingtodo As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _wheniplaywithfriendswe As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _whenathomeihelpoutby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _whenitalktogodiaskhim As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _somedayi As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _twomostfavoritethings As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _otherthingsthechildenjoys As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    ' Child Personality moved to Development Tab
    'Private WithEvents _childpersonality As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _myfavoritethingtodo = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _wheniplaywithfriendswe = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _whenathomeihelpoutby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _whenitalktogodiaskhim = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _somedayi = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _twomostfavoritethings = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _otherthingsthechildenjoys = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        '_childpersonality = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("29385eae-7328-4c26-be11-657455d48a09")
        MyBase.DataFormInstanceId = New Guid("55f5b7f0-5207-40c6-ba5a-5907a7721aa7")
        MyBase.RecordType = "Child Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/ChildExtensionAboutMeEditDataForm.html"

        '
        '_myfavoritethingtodo
        '
        _myfavoritethingtodo.Name = "MYFAVORITETHINGTODO"
        _myfavoritethingtodo.Caption = "My favorite thing to do when I am by myself is"
        _myfavoritethingtodo.MaxLength = 1000
        _myfavoritethingtodo.MultiLine = True
        Me.Fields.Add(_myfavoritethingtodo)
        '
        '_wheniplaywithfriendswe
        '
        _wheniplaywithfriendswe.Name = "WHENIPLAYWITHFRIENDSWE"
        _wheniplaywithfriendswe.Caption = "When I play with my friends we"
        _wheniplaywithfriendswe.MaxLength = 1000
        _wheniplaywithfriendswe.MultiLine = True
        Me.Fields.Add(_wheniplaywithfriendswe)
        '
        '_whenathomeihelpoutby
        '
        _whenathomeihelpoutby.Name = "WHENATHOMEIHELPOUTBY"
        _whenathomeihelpoutby.Caption = "When at home I help out by"
        _whenathomeihelpoutby.MaxLength = 1000
        _whenathomeihelpoutby.MultiLine = True
        Me.Fields.Add(_whenathomeihelpoutby)
        '
        '_whenitalktogodiaskhim
        '
        _whenitalktogodiaskhim.Name = "WHENITALKTOGODIASKHIM"
        _whenitalktogodiaskhim.Caption = "When I talk to God I ask Him"
        _whenitalktogodiaskhim.MaxLength = 1000
        _whenitalktogodiaskhim.MultiLine = True
        Me.Fields.Add(_whenitalktogodiaskhim)
        '
        '_somedayi
        '
        _somedayi.Name = "SOMEDAYI"
        _somedayi.Caption = "Someday I would like"
        _somedayi.MaxLength = 1000
        _somedayi.MultiLine = True
        Me.Fields.Add(_somedayi)
        '
        '_twomostfavoritethings
        '
        _twomostfavoritethings.Name = "TWOMOSTFAVORITETHINGS"
        _twomostfavoritethings.Caption = "My most favorite things"
        _twomostfavoritethings.MaxLength = 1000
        _twomostfavoritethings.MultiLine = True
        Me.Fields.Add(_twomostfavoritethings)
        '
        '_otherthingsthechildenjoys
        '
        _otherthingsthechildenjoys.Name = "OTHERTHINGSTHECHILDENJOYS"
        _otherthingsthechildenjoys.Caption = "Other things the child enjoys"
        _otherthingsthechildenjoys.MaxLength = 1000
        _otherthingsthechildenjoys.MultiLine = True
        Me.Fields.Add(_otherthingsthechildenjoys)
        ''
        ''_childpersonality
        ''
        '_childpersonality.Name = "CHILDPERSONALITY"
        '_childpersonality.Caption = "Child's personality or quallities and how they interact with other children"
        '_childpersonality.MaxLength = 1000
        '_childpersonality.MultiLine = True
        'Me.Fields.Add(_childpersonality)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' My favorite thing to do when I am by myself is
    ''' </summary>
    <System.ComponentModel.Description("My favorite thing to do when I am by myself is")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MYFAVORITETHINGTODO]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _myfavoritethingtodo
        End Get
    End Property
    
    ''' <summary>
    ''' When I play with my friends we
    ''' </summary>
    <System.ComponentModel.Description("When I play with my friends we")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHENIPLAYWITHFRIENDSWE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _wheniplaywithfriendswe
        End Get
    End Property
    
    ''' <summary>
    ''' When at home I help out by
    ''' </summary>
    <System.ComponentModel.Description("When at home I help out by")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHENATHOMEIHELPOUTBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _whenathomeihelpoutby
        End Get
    End Property
    
    ''' <summary>
    ''' When I talk to God I ask Him
    ''' </summary>
    <System.ComponentModel.Description("When I talk to God I ask Him")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [WHENITALKTOGODIASKHIM]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _whenitalktogodiaskhim
        End Get
    End Property
    
    ''' <summary>
    ''' Someday I would like
    ''' </summary>
    <System.ComponentModel.Description("Someday I would like")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOMEDAYI]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _somedayi
        End Get
    End Property
    
    ''' <summary>
    ''' My most favorite things
    ''' </summary>
    <System.ComponentModel.Description("My most favorite things")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [TWOMOSTFAVORITETHINGS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _twomostfavoritethings
        End Get
    End Property
    
    ''' <summary>
    ''' Other things the child enjoys
    ''' </summary>
    <System.ComponentModel.Description("Other things the child enjoys")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [OTHERTHINGSTHECHILDENJOYS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _otherthingsthechildenjoys
        End Get
    End Property
    
    '''' <summary>
    '''' Child's personality or quallities and how they interact with other children
    '''' </summary>
    '<System.ComponentModel.Description("Child's personality or quallities and how they interact with other children")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [CHILDPERSONALITY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    '    Get
    '        Return _childpersonality
    '    End Get
    'End Property
    
End Class
