Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'CCH ChildExtension Who I live with Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "f4268ab8-815e-4771-bc6f-2ba4e86a63eb", "3626cd83-acd8-4277-9fd4-96477d76e385", "Child Extension")> _
Partial Public Class [ChildExtensionWhoILiveWithViewFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _childliveswithcode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _fatherworksascode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _fatherworksasother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _motherworksascode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _motherworksasother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverrelationcode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverrelationother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverworksascode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverworksasother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _caregiverreasoncode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _reasonforcaregiverother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _numberofsisters As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _numberofbrothers As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _sponsorshipopportunitychildid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _parentalinformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _caregiverinformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _siblinginformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _childliveswithcode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _fatherworksascode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _fatherworksasother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _motherworksascode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _motherworksasother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverrelationcode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverrelationother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverworksascode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverworksasother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _caregiverreasoncode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _reasonforcaregiverother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _numberofsisters = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _numberofbrothers = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _sponsorshipopportunitychildid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _parentalinformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _caregiverinformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _siblinginformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("f4268ab8-815e-4771-bc6f-2ba4e86a63eb")
        MyBase.DataFormInstanceId = New Guid("3626cd83-acd8-4277-9fd4-96477d76e385")
        MyBase.RecordType = "Child Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildExtensionWhoILiveWithViewForm.html"

        '
        '_childliveswithcode
        '
        _childliveswithcode.Name = "CHILDLIVESWITHCODE"
        _childliveswithcode.Caption = "Child Lives With"
        _childliveswithcode.DBReadOnly = True
        Me.Fields.Add(_childliveswithcode)
        '
        '_fatherworksascode
        '
        _fatherworksascode.Name = "FATHERWORKSASCODE"
        _fatherworksascode.Caption = "Father Works As"
        _fatherworksascode.DBReadOnly = True
        Me.Fields.Add(_fatherworksascode)
        '
        '_fatherworksasother
        '
        _fatherworksasother.Name = "FATHERWORKSASOTHER"
        _fatherworksasother.Caption = "Details/Other"
        _fatherworksasother.DBReadOnly = True
        _fatherworksasother.MaxLength = 50
        Me.Fields.Add(_fatherworksasother)
        '
        '_motherworksascode
        '
        _motherworksascode.Name = "MOTHERWORKSASCODE"
        _motherworksascode.Caption = "Mother Works As"
        _motherworksascode.DBReadOnly = True
        Me.Fields.Add(_motherworksascode)
        '
        '_motherworksasother
        '
        _motherworksasother.Name = "MOTHERWORKSASOTHER"
        _motherworksasother.Caption = "Details/Other"
        _motherworksasother.DBReadOnly = True
        _motherworksasother.MaxLength = 50
        Me.Fields.Add(_motherworksasother)
        '
        '_caregiverrelationcode
        '
        _caregiverrelationcode.Name = "CAREGIVERRELATIONCODE"
        _caregiverrelationcode.Caption = "Caregiver Relation"
        _caregiverrelationcode.DBReadOnly = True
        Me.Fields.Add(_caregiverrelationcode)
        '
        '_caregiverrelationother
        '
        _caregiverrelationother.Name = "CAREGIVERRELATIONOTHER"
        _caregiverrelationother.Caption = "Details/Other"
        _caregiverrelationother.DBReadOnly = True
        _caregiverrelationother.MaxLength = 50
        Me.Fields.Add(_caregiverrelationother)
        '
        '_caregiverworksascode
        '
        _caregiverworksascode.Name = "CAREGIVERWORKSASCODE"
        _caregiverworksascode.Caption = "Caregiver Works As"
        _caregiverworksascode.DBReadOnly = True
        Me.Fields.Add(_caregiverworksascode)
        '
        '_caregiverworksasother
        '
        _caregiverworksasother.Name = "CAREGIVERWORKSASOTHER"
        _caregiverworksasother.Caption = "Details/Other"
        _caregiverworksasother.DBReadOnly = True
        _caregiverworksasother.MaxLength = 50
        Me.Fields.Add(_caregiverworksasother)
        '
        '_caregiverreasoncode
        '
        _caregiverreasoncode.Name = "CAREGIVERREASONCODE"
        _caregiverreasoncode.Caption = "Reason for Caregiver"
        _caregiverreasoncode.DBReadOnly = True
        Me.Fields.Add(_caregiverreasoncode)
        '
        '_reasonforcaregiverother
        '
        _reasonforcaregiverother.Name = "REASONFORCAREGIVEROTHER"
        _reasonforcaregiverother.Caption = "Details/Other"
        _reasonforcaregiverother.DBReadOnly = True
        _reasonforcaregiverother.MaxLength = 50
        Me.Fields.Add(_reasonforcaregiverother)
        '
        '_numberofsisters
        '
        _numberofsisters.Name = "NUMBEROFSISTERS"
        _numberofsisters.Caption = "Number of Sisters"
        _numberofsisters.DBReadOnly = True
        Me.Fields.Add(_numberofsisters)
        '
        '_numberofbrothers
        '
        _numberofbrothers.Name = "NUMBEROFBROTHERS"
        _numberofbrothers.Caption = "Number of Brothers"
        _numberofbrothers.DBReadOnly = True
        Me.Fields.Add(_numberofbrothers)
        '
        '_sponsorshipopportunitychildid
        '
        _sponsorshipopportunitychildid.Name = "SPONSORSHIPOPPORTUNITYCHILDID"
        _sponsorshipopportunitychildid.Caption = "SPONSORSHIPOPPORTUNITYCHILDID"
        _sponsorshipopportunitychildid.Visible = False
        _sponsorshipopportunitychildid.DBReadOnly = True
        Me.Fields.Add(_sponsorshipopportunitychildid)
        '
        '_parentalinformationgroup
        '
        _parentalinformationgroup.Name = "PARENTALINFORMATION_GROUP"
        _parentalinformationgroup.Caption = "Parental Information"
        _parentalinformationgroup.Fields.Add("CHILDLIVESWITHCODE")
        _parentalinformationgroup.Fields.Add("FATHERWORKSASCODE")
        _parentalinformationgroup.Fields.Add("MOTHERWORKSASCODE")
        _parentalinformationgroup.Fields.Add("FATHERWORKSASOTHER")
        _parentalinformationgroup.Fields.Add("MOTHERWORKSASOTHER")
        Me.Fields.Add(_parentalinformationgroup)
        '
        '_caregiverinformationgroup
        '
        _caregiverinformationgroup.Name = "CAREGIVERINFORMATION_GROUP"
        _caregiverinformationgroup.Caption = "Caregiver Information"
        _caregiverinformationgroup.Fields.Add("CAREGIVERRELATIONCODE")
        _caregiverinformationgroup.Fields.Add("CAREGIVERWORKSASCODE")
        _caregiverinformationgroup.Fields.Add("CAREGIVERREASONCODE")
        _caregiverinformationgroup.Fields.Add("CAREGIVERRELATIONOTHER")
        _caregiverinformationgroup.Fields.Add("CAREGIVERWORKSASOTHER")
        _caregiverinformationgroup.Fields.Add("REASONFORCAREGIVEROTHER")
        Me.Fields.Add(_caregiverinformationgroup)
        '
        '_siblinginformationgroup
        '
        _siblinginformationgroup.Name = "SIBLING_INFORMATION_GROUP"
        _siblinginformationgroup.Caption = "Sibling Information"
        _siblinginformationgroup.Fields.Add("NUMBEROFSISTERS")
        _siblinginformationgroup.Fields.Add("NUMBEROFBROTHERS")
        Me.Fields.Add(_siblinginformationgroup)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Child Lives With
    ''' </summary>
    <System.ComponentModel.Description("Child Lives With")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDLIVESWITHCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childliveswithcode
        End Get
    End Property
    
    ''' <summary>
    ''' Father Works As
    ''' </summary>
    <System.ComponentModel.Description("Father Works As")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FATHERWORKSASCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _fatherworksascode
        End Get
    End Property
    
    ''' <summary>
    ''' Father Works As other value
    ''' </summary>
    <System.ComponentModel.Description("Details/Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FATHERWORKSASOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _fatherworksasother
        End Get
    End Property
    
    ''' <summary>
    ''' Mother Works As
    ''' </summary>
    <System.ComponentModel.Description("Mother Works As")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MOTHERWORKSASCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _motherworksascode
        End Get
    End Property
    
    ''' <summary>
    ''' Mother Works As other value
    ''' </summary>
    <System.ComponentModel.Description("Details/Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [MOTHERWORKSASOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _motherworksasother
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Relation
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Relation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERRELATIONCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverrelationcode
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Relation other value
    ''' </summary>
    <System.ComponentModel.Description("Details/Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERRELATIONOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverrelationother
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Works As
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Works As")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERWORKSASCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverworksascode
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Works As other value
    ''' </summary>
    <System.ComponentModel.Description("Details/Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERWORKSASOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverworksasother
        End Get
    End Property
    
    ''' <summary>
    ''' Reason for Caregiver
    ''' </summary>
    <System.ComponentModel.Description("Reason for Caregiver")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERREASONCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _caregiverreasoncode
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Reason other value
    ''' </summary>
    <System.ComponentModel.Description("Details/Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [REASONFORCAREGIVEROTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _reasonforcaregiverother
        End Get
    End Property
    
    ''' <summary>
    ''' Number of Sisters
    ''' </summary>
    <System.ComponentModel.Description("Number of Sisters")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NUMBEROFSISTERS]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _numberofsisters
        End Get
    End Property
    
    ''' <summary>
    ''' Number of Brothers
    ''' </summary>
    <System.ComponentModel.Description("Number of Brothers")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NUMBEROFBROTHERS]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _numberofbrothers
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipopportunitychildid
        End Get
    End Property
    
    ''' <summary>
    ''' Parental Information
    ''' </summary>
    <System.ComponentModel.Description("Parental Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PARENTALINFORMATION_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _parentalinformationgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Caregiver Information
    ''' </summary>
    <System.ComponentModel.Description("Caregiver Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CAREGIVERINFORMATION_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _caregiverinformationgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Sibling Information
    ''' </summary>
    <System.ComponentModel.Description("Sibling Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SIBLING_INFORMATION_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _siblinginformationgroup
        End Get
    End Property
    
End Class
