Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'TestBatchEditForm Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "6cb43c6f-955a-4cd8-a561-8ddbe55e9143", "92fd5111-7aaa-49bc-987a-bafbc78a1949", "BATCHTEST")> _
Partial Public Class [TestBatchEditFormEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sequence As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _testname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _sponsorshiplocationid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _testflag As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _testdescription As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _sequence = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _testname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _sponsorshiplocationid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _testflag = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _testdescription = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("6cb43c6f-955a-4cd8-a561-8ddbe55e9143")
        MyBase.DataFormInstanceId = New Guid("92fd5111-7aaa-49bc-987a-bafbc78a1949")
        MyBase.RecordType = "BATCHTEST"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/TestBatchEditFormEditDataForm.html"

        '
        '_sequence
        '
        _sequence.Name = "SEQUENCE"
        _sequence.Caption = "Sequence"
        _sequence.Required = True
        _sequence.Visible = False
        Me.Fields.Add(_sequence)
        '
        '_testname
        '
        _testname.Name = "TESTNAME"
        _testname.Caption = "TESTNAME"
        _testname.Description = "Name"
        _testname.Required = True
        _testname.MaxLength = 200
        Me.Fields.Add(_testname)
        '
        '_sponsorshiplocationid
        '
        _sponsorshiplocationid.Name = "SPONSORSHIPLOCATIONID"
        _sponsorshiplocationid.Caption = "Location"
        _sponsorshiplocationid.Required = True
        _sponsorshiplocationid.SearchListID = New Guid("7d7ac450-86f7-42f7-9299-e2458592ad14")
        _sponsorshiplocationid.EnableQuickFind = True
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "INCLUDECHILDNODES", .DefaultValueText = "1"})
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "WITHINLOCATION", .Hidden = True})
        _sponsorshiplocationid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "WITHINLOCATIONDISPLAY", .Hidden = True})
        Me.Fields.Add(_sponsorshiplocationid)
        '
        '_testflag
        '
        _testflag.Name = "TESTFLAG"
        _testflag.Caption = "Testing?"
        Me.Fields.Add(_testflag)
        '
        '_testdescription
        '
        _testdescription.Name = "TESTDESCRIPTION"
        _testdescription.Caption = "Description of Test"
        _testdescription.MaxLength = 100
        Me.Fields.Add(_testdescription)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Sequence
    ''' </summary>
    <System.ComponentModel.Description("Sequence")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SEQUENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _sequence
        End Get
    End Property
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [TESTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _testname
        End Get
    End Property
    
    ''' <summary>
    ''' Location
    ''' </summary>
    <System.ComponentModel.Description("Location")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPONSORSHIPLOCATIONID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshiplocationid
        End Get
    End Property
    
    ''' <summary>
    ''' Testing?
    ''' </summary>
    <System.ComponentModel.Description("Testing?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [TESTFLAG]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _testflag
        End Get
    End Property
    
    ''' <summary>
    ''' Description of Test
    ''' </summary>
    <System.ComponentModel.Description("Description of Test")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [TESTDESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _testdescription
        End Get
    End Property
    
End Class
