Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture Spiritual and Physical Impact Tab Edit Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "11210e94-a768-43d7-b73c-05ab0fe28728", "72121a1e-2b21-45e9-a334-012fae466e6a", "ChildDeparture")> _
Partial Public Class [ChildDepartureSpiritualAndPhysicalImpactTabEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the ISCHILDCHRISTIANCODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum ISCHILDCHRISTIANCODES As Integer
        [No] = 0
        [Yes] = 1
        [Unknown] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the DIDBECOMECHRISTIANCODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum DIDBECOMECHRISTIANCODES As Integer
        [No] = 0
        [Yes] = 1
        [Unknown] = 2
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _ischildchristiancode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISCHILDCHRISTIANCODES))
    Private WithEvents _childchristiancomments As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _didbecomechristiancode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DIDBECOMECHRISTIANCODES))
    Private WithEvents _showschristianknowledge As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participateschristianactivities As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _showschristianevidence As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _ownsbiblematerials As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childchristianexperience As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _healthconditions As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _ischildchristiancode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISCHILDCHRISTIANCODES))
        _childchristiancomments = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _didbecomechristiancode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DIDBECOMECHRISTIANCODES))
        _showschristianknowledge = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participateschristianactivities = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _showschristianevidence = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _ownsbiblematerials = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childchristianexperience = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _healthconditions = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("11210e94-a768-43d7-b73c-05ab0fe28728")
        MyBase.DataFormInstanceId = New Guid("72121a1e-2b21-45e9-a334-012fae466e6a")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureSpiritualAndPhysicalImpactTabEditForm.html"

        '
        '_ischildchristiancode
        '
        _ischildchristiancode.Name = "ISCHILDCHRISTIANCODE"
        _ischildchristiancode.Caption = "Child is a Christian"
        _ischildchristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[No], .Translation = "No"})
        _ischildchristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[Yes], .Translation = "Yes"})
        _ischildchristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[Unknown], .Translation = "Unknown"})
        Me.Fields.Add(_ischildchristiancode)
        '
        '_childchristiancomments
        '
        _childchristiancomments.Name = "CHILDCHRISTIANCOMMENTS"
        _childchristiancomments.Caption = "Comments"
        _childchristiancomments.MaxLength = 50
        Me.Fields.Add(_childchristiancomments)
        '
        '_didbecomechristiancode
        '
        _didbecomechristiancode.Name = "DIDBECOMECHRISTIANCODE"
        _didbecomechristiancode.Caption = "Child became a Christian while in the sponsorship program"
        _didbecomechristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[No], .Translation = "No"})
        _didbecomechristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[Yes], .Translation = "Yes"})
        _didbecomechristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[Unknown], .Translation = "Unknown"})
        Me.Fields.Add(_didbecomechristiancode)
        '
        '_showschristianknowledge
        '
        _showschristianknowledge.Name = "SHOWSCHRISTIANKNOWLEDGE"
        _showschristianknowledge.Caption = "Child shows some knowledge of the Christian faith"
        Me.Fields.Add(_showschristianknowledge)
        '
        '_participateschristianactivities
        '
        _participateschristianactivities.Name = "PARTICIPATESCHRISTIANACTIVITIES"
        _participateschristianactivities.Caption = "Child sometimes participates in Christian activities, but does not lead those activities"
        Me.Fields.Add(_participateschristianactivities)
        '
        '_showschristianevidence
        '
        _showschristianevidence.Name = "SHOWSCHRISTIANEVIDENCE"
        _showschristianevidence.Caption = "Child shows some evidence of Christian faith and behavior"
        Me.Fields.Add(_showschristianevidence)
        '
        '_ownsbiblematerials
        '
        _ownsbiblematerials.Name = "OWNSBIBLEMATERIALS"
        _ownsbiblematerials.Caption = "Child has Scripture materials"
        Me.Fields.Add(_ownsbiblematerials)
        '
        '_childchristianexperience
        '
        _childchristianexperience.Name = "CHILDCHRISTIANEXPERIENCE"
        _childchristianexperience.Caption = "Provide a detailed explanation of the child's Christian experience"
        _childchristianexperience.MaxLength = 1000
        _childchristianexperience.MultiLine = True
        Me.Fields.Add(_childchristianexperience)
        '
        '_healthconditions
        '
        _healthconditions.Name = "HEALTHCONDITIONS"
        _healthconditions.Caption = "Note any illnesses the child had during their participaton in the program as well as what the child's current health is"
        _healthconditions.MaxLength = 1000
        _healthconditions.MultiLine = True
        _healthconditions.AllowZoom = True
        Me.Fields.Add(_healthconditions)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Child is a Christian
    ''' </summary>
    <System.ComponentModel.Description("Child is a Christian")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISCHILDCHRISTIANCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISCHILDCHRISTIANCODES))
        Get
            Return _ischildchristiancode
        End Get
    End Property
    
    ''' <summary>
    ''' Comments
    ''' </summary>
    <System.ComponentModel.Description("Comments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCHRISTIANCOMMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childchristiancomments
        End Get
    End Property
    
    ''' <summary>
    ''' Child became a Christian while in the sponsorship program
    ''' </summary>
    <System.ComponentModel.Description("Child became a Christian while in the sponsorship program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DIDBECOMECHRISTIANCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DIDBECOMECHRISTIANCODES))
        Get
            Return _didbecomechristiancode
        End Get
    End Property
    
    ''' <summary>
    ''' Child shows some knowledge of the Christian faith
    ''' </summary>
    <System.ComponentModel.Description("Child shows some knowledge of the Christian faith")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SHOWSCHRISTIANKNOWLEDGE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showschristianknowledge
        End Get
    End Property
    
    ''' <summary>
    ''' Child sometimes participates in Christian activities, but does not lead those activities
    ''' </summary>
    <System.ComponentModel.Description("Child sometimes participates in Christian activities, but does not lead those activities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PARTICIPATESCHRISTIANACTIVITIES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participateschristianactivities
        End Get
    End Property
    
    ''' <summary>
    ''' Child shows some evidence of Christian faith and behavior
    ''' </summary>
    <System.ComponentModel.Description("Child shows some evidence of Christian faith and behavior")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SHOWSCHRISTIANEVIDENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showschristianevidence
        End Get
    End Property
    
    ''' <summary>
    ''' Child has Scripture materials
    ''' </summary>
    <System.ComponentModel.Description("Child has Scripture materials")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [OWNSBIBLEMATERIALS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _ownsbiblematerials
        End Get
    End Property
    
    ''' <summary>
    ''' Provide a detailed explanation of the child's Christian experience
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's Christian experience")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCHRISTIANEXPERIENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childchristianexperience
        End Get
    End Property
    
    ''' <summary>
    ''' Note any illnesses the child had during their participaton in the program as well as what the child's current health is
    ''' </summary>
    <System.ComponentModel.Description("Note any illnesses the child had during their participaton in the program as well as what the child's current health is")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HEALTHCONDITIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _healthconditions
        End Get
    End Property
    
End Class
