Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture General Comments View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "085d83f4-38b1-43e5-9e1a-8d2622913a5c", "fd694a10-d47d-41ec-a82c-5b56ede13c2d", "ChildDeparture")> _
Partial Public Class [ChildDepartureGeneralCommentsViewFormUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _generalcomments As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _generalcomments = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("085d83f4-38b1-43e5-9e1a-8d2622913a5c")
        MyBase.DataFormInstanceId = New Guid("fd694a10-d47d-41ec-a82c-5b56ede13c2d")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureGeneralCommentsViewForm.html"

        '
        '_generalcomments
        '
        _generalcomments.Name = "GENERALCOMMENTS"
        _generalcomments.Caption = "Generalcomments"
        _generalcomments.DBReadOnly = True
        _generalcomments.MaxLength = 1000
        _generalcomments.MultiLine = True
        _generalcomments.AllowZoom = True
        Me.Fields.Add(_generalcomments)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Generalcomments
    ''' </summary>
    <System.ComponentModel.Description("Generalcomments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GENERALCOMMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _generalcomments
        End Get
    End Property

End Class
