Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture SocialCognitive Impact View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "d3186dbe-caf2-4fc2-a7d6-60750e3bc8ef", "68c8570f-6ba2-45f5-807b-1f712f31e414", "ChildDeparture")> _
Partial Public Class [ChildDepartureSocialCognitiveImpactViewFormUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the CHILDMATUREDCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum CHILDMATUREDCODES As Integer
        [No] = 0
        [Yes] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _childmatured As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _levelofmaturity As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _highestclasslevelcode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _highestclasslevelother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _courseofstudy As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _skillsbasicliteracy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsbasicnumeracy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsthinkingproblemsolving As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsselfhelp As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsbusiness As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillslife As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsvocationaltechnical As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsother As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _childmatured = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _levelofmaturity = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _highestclasslevelcode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _highestclasslevelother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _courseofstudy = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _skillsbasicliteracy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsbasicnumeracy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsthinkingproblemsolving = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsselfhelp = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsbusiness = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillslife = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsvocationaltechnical = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("d3186dbe-caf2-4fc2-a7d6-60750e3bc8ef")
        MyBase.DataFormInstanceId = New Guid("68c8570f-6ba2-45f5-807b-1f712f31e414")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureSocialCognitiveImpactViewForm.html"

        '
        '_childmaturedcode
        '
        _childmatured.Name = "CHILDMATURED"
        _childmatured.Caption = "Child has matured appropriately for their age"
        _childmatured.DBReadOnly = True
        '_childmaturedcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of CHILDMATUREDCODES)) With {.Value = CHILDMATUREDCODES.[No], .Translation = "No"})
        '_childmaturedcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of CHILDMATUREDCODES)) With {.Value = CHILDMATUREDCODES.[Yes], .Translation = "Yes"})
        '_childmaturedcode.Value = CHILDMATUREDCODES.[No]
        Me.Fields.Add(_childmatured)
        '
        '_levelofmaturity
        '
        _levelofmaturity.Name = DepartureFieldNames.LEVELOFMATURITY.ToString()
        _levelofmaturity.Caption = "Provide a brief explanation of the chlid's level of maturity and how they relate to others around them"
        _levelofmaturity.DBReadOnly = True
        _levelofmaturity.MaxLength = 1000
        _levelofmaturity.MultiLine = True
        _levelofmaturity.AllowZoom = True
        Me.Fields.Add(_levelofmaturity)
        '
        '_highestclasslevelcodeid
        '
        _highestclasslevelcode.Name = "HIGHESTCLASSLEVELCODE"
        _highestclasslevelcode.Caption = "Highest Class Level Completed"
        _highestclasslevelcode.DBReadOnly = True
        '_highestclasslevelcodeid.CodeTableName = "USR_CHILDCLASSLEVEL_CODE"
        Me.Fields.Add(_highestclasslevelcode)
        '
        '_highestclasslevelother
        '
        _highestclasslevelother.Name = DepartureFieldNames.HIGHESTCLASSLEVELOTHER.ToString()
        _highestclasslevelother.Caption = "Other"
        _highestclasslevelother.DBReadOnly = True
        _highestclasslevelother.MaxLength = 20
        Me.Fields.Add(_highestclasslevelother)
        '
        '_courseofstudy
        '
        _courseofstudy.Name = DepartureFieldNames.COURSEOFSTUDY.ToString()
        _courseofstudy.Caption = "Course of Study"
        _courseofstudy.DBReadOnly = True
        _courseofstudy.MaxLength = 50
        Me.Fields.Add(_courseofstudy)
        '
        '_skillsbasicliteracy
        '
        _skillsbasicliteracy.Name = DepartureFieldNames.SKILLS_BASICLITERACY.ToString()
        _skillsbasicliteracy.Caption = "Basic Literacy"
        _skillsbasicliteracy.DBReadOnly = True
        Me.Fields.Add(_skillsbasicliteracy)
        '
        '_skillsbasicnumeracy
        '
        _skillsbasicnumeracy.Name = DepartureFieldNames.SKILLS_BASICNUMERACY.ToString()
        _skillsbasicnumeracy.Caption = "Basic Numeracy"
        _skillsbasicnumeracy.DBReadOnly = True
        Me.Fields.Add(_skillsbasicnumeracy)
        '
        '_skillsthinkingproblemsolving
        '
        _skillsthinkingproblemsolving.Name = DepartureFieldNames.SKILLS_THINKINGPROBLEMSOLVING.ToString()
        _skillsthinkingproblemsolving.Caption = "Thinking and problem-solving skills"
        _skillsthinkingproblemsolving.DBReadOnly = True
        Me.Fields.Add(_skillsthinkingproblemsolving)
        '
        '_skillsselfhelp
        '
        _skillsselfhelp.Name = DepartureFieldNames.SKILLS_SELFHELP.ToString()
        _skillsselfhelp.Caption = "Self-help Skills"
        _skillsselfhelp.DBReadOnly = True
        Me.Fields.Add(_skillsselfhelp)
        '
        '_skillsbusiness
        '
        _skillsbusiness.Name = DepartureFieldNames.SKILLS_BUSINESS.ToString()
        _skillsbusiness.Caption = "Entrepreneurial (business) skills"
        _skillsbusiness.DBReadOnly = True
        Me.Fields.Add(_skillsbusiness)
        '
        '_skillslife
        '
        _skillslife.Name = DepartureFieldNames.SKILLS_LIFE.ToString()
        _skillslife.Caption = "Life Skills"
        _skillslife.DBReadOnly = True
        Me.Fields.Add(_skillslife)
        '
        '_skillsvocationaltechnical
        '
        _skillsvocationaltechnical.Name = DepartureFieldNames.SKILLS_VOCATIONALTECHNICAL.ToString()
        _skillsvocationaltechnical.Caption = "Vocational and Technical Skills"
        _skillsvocationaltechnical.DBReadOnly = True
        Me.Fields.Add(_skillsvocationaltechnical)
        '
        '_skillsother
        '
        _skillsother.Name = DepartureFieldNames.SKILLS_OTHER.ToString()
        _skillsother.Caption = "Other Skills"
        _skillsother.DBReadOnly = True
        _skillsother.MaxLength = 50
        Me.Fields.Add(_skillsother)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Child has matured appropriately for their age
    ''' </summary>
    <System.ComponentModel.Description("Child has matured appropriately for their age")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDMATURED]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childmatured
        End Get
    End Property

    ''' <summary>
    ''' Provide a brief explanation of the chlid's level of maturity and how they relate to others around them
    ''' </summary>
    <System.ComponentModel.Description("Provide a brief explanation of the chlid's level of maturity and how they relate to others around them")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LEVELOFMATURITY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _levelofmaturity
        End Get
    End Property

    ''' <summary>
    ''' Highest Class Level Completed
    ''' </summary>
    <System.ComponentModel.Description("Highest Class Level Completed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTCLASSLEVELCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _highestclasslevelcode
        End Get
    End Property

    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTCLASSLEVELOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _highestclasslevelother
        End Get
    End Property

    ''' <summary>
    ''' Course of Study
    ''' </summary>
    <System.ComponentModel.Description("Course of Study")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COURSEOFSTUDY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _courseofstudy
        End Get
    End Property

    ''' <summary>
    ''' Basic Literacy
    ''' </summary>
    <System.ComponentModel.Description("Basic Literacy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_BASICLITERACY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsbasicliteracy
        End Get
    End Property

    ''' <summary>
    ''' Basic Numeracy
    ''' </summary>
    <System.ComponentModel.Description("Basic Numeracy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_BASICNUMERACY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsbasicnumeracy
        End Get
    End Property

    ''' <summary>
    ''' Thinking and problem-solving skills
    ''' </summary>
    <System.ComponentModel.Description("Thinking and problem-solving skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_THINKINGPROBLEMSOLVING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsthinkingproblemsolving
        End Get
    End Property

    ''' <summary>
    ''' Self-help Skills
    ''' </summary>
    <System.ComponentModel.Description("Self-help Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_SELFHELP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsselfhelp
        End Get
    End Property

    ''' <summary>
    ''' Entrepreneurial (business) skills
    ''' </summary>
    <System.ComponentModel.Description("Entrepreneurial (business) skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_BUSINESS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsbusiness
        End Get
    End Property

    ''' <summary>
    ''' Life Skills
    ''' </summary>
    <System.ComponentModel.Description("Life Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_LIFE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillslife
        End Get
    End Property

    ''' <summary>
    ''' Vocational and Technical Skills
    ''' </summary>
    <System.ComponentModel.Description("Vocational and Technical Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_VOCATIONALTECHNICAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsvocationaltechnical
        End Get
    End Property

    ''' <summary>
    ''' Other Skills
    ''' </summary>
    <System.ComponentModel.Description("Other Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_OTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _skillsother
        End Get
    End Property

End Class
