Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture Add Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "3ffc5e3b-371b-4c08-aa0d-240b520991ee", "ac89e520-149a-4a66-83c2-1e5e906a5809", "ChildDeparture")> _
Partial Public Class [ChildDepartureAddFormUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the RECEIVEDFAREWELLLETTERCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum RECEIVEDFAREWELLLETTERCODES As Integer
        [No] = 0
        [Yes] = 1
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the ISCHILDCHRISTIANCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum ISCHILDCHRISTIANCODES As Integer
        [No] = 0
        [Yes] = 1
        [Unknown] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the DIDBECOMECHRISTIANCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum DIDBECOMECHRISTIANCODES As Integer
        [No] = 0
        [Yes] = 1
        [Unknown] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the CHILDMATUREDCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum CHILDMATUREDCODES As Integer
        [No] = 0
        [Yes] = 1
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the DEPARTURETYPECODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum DEPARTURETYPECODES As Integer
        [Departure] = 0
        [Completion] = 1
        [Administrative] = 2
    End Enum


#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sponsorshipopportunitychildid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _nodepartureform As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuretypecode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DEPARTURETYPECODES))
    Private WithEvents _receivedfarewelllettercode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES))
    Private WithEvents _dateformcompleted As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _formcompletedby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _dateofdeparture As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _dateprocessed As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _administrativecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _administrativeexplanation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _isdeparture As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _isprogramcompletion As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureliveswithrelatives As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefamilymoved As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefamilynowprovides As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureprojecttoofar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureremovedbyparents As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurelackofinterest As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureneededathome As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureemployed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuretransferred As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefailed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuredeathofchild As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureillness As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurepregnancy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuremarried As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _detailedexplanation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _departurenewsituation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _programcompletionnewsituation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _ischildchristiancode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISCHILDCHRISTIANCODES))
    Private WithEvents _childchristiancomments As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _didbecomechristiancode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DIDBECOMECHRISTIANCODES))
    Private WithEvents _showschristianknowledge As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participateschristianactivities As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _showschristianevidence As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _ownsbiblematerials As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childchristianexperience As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _healthconditions As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childmaturedcode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of CHILDMATUREDCODES))
    Private WithEvents _levelofmaturity As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _highestclasslevelcodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _highestclasslevelother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _courseofstudy As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _skillsbasicliteracy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsbasicnumeracy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsthinkingproblemsolving As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsselfhelp As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsbusiness As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillslife As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsvocationaltechnical As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _skillsother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _generalcomments As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _generalinfogroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _departurereasonstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _spiritualphysicaltab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _socialcognitivetab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _commentstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _sponsorshipopportunitychildid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _nodepartureform = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuretypecode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DEPARTURETYPECODES))
        _receivedfarewelllettercode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES))
        _dateformcompleted = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _formcompletedby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _dateofdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _dateprocessed = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _administrativecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _administrativeexplanation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _isdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _isprogramcompletion = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureliveswithrelatives = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefamilymoved = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefamilynowprovides = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureprojecttoofar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureremovedbyparents = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurelackofinterest = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureneededathome = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureemployed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuretransferred = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefailed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuredeathofchild = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureillness = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurepregnancy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuremarried = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _detailedexplanation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _departurenewsituation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _programcompletionnewsituation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _ischildchristiancode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISCHILDCHRISTIANCODES))
        _childchristiancomments = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _didbecomechristiancode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DIDBECOMECHRISTIANCODES))
        _showschristianknowledge = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participateschristianactivities = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _showschristianevidence = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _ownsbiblematerials = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childchristianexperience = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _healthconditions = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childmaturedcode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of CHILDMATUREDCODES))
        _levelofmaturity = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _highestclasslevelcodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _highestclasslevelother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _courseofstudy = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _skillsbasicliteracy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsbasicnumeracy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsthinkingproblemsolving = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsselfhelp = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsbusiness = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillslife = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsvocationaltechnical = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _skillsother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _generalcomments = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _generalinfogroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _departurereasonstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _spiritualphysicaltab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _socialcognitivetab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _commentstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("3ffc5e3b-371b-4c08-aa0d-240b520991ee")
        MyBase.DataFormInstanceId = New Guid("ac89e520-149a-4a66-83c2-1e5e906a5809")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureAddForm.html"

        ''
        ''_sponsorshipopportunitychildid
        ''
        '_sponsorshipopportunitychildid.Name = "SPONSORSHIPOPPORTUNITYCHILDID"
        '_sponsorshipopportunitychildid.Caption = "Sponsorshipopportunitychild"
        '_sponsorshipopportunitychildid.Required = False
        '_sponsorshipopportunitychildid.Visible = False
        'Me.Fields.Add(_sponsorshipopportunitychildid)
        '
        '_nodepartureform
        '
        _nodepartureform.Name = "NODEPARTUREFORM"
        _nodepartureform.Caption = "No Departure Form"
        Me.Fields.Add(_nodepartureform)
        '
        '_departuretypecode
        '
        _departuretypecode.Name = "DEPARTURETYPECODE"
        _departuretypecode.Caption = "Type of departure"
        _departuretypecode.Required = True
        _departuretypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DEPARTURETYPECODES)) With {.Value = DEPARTURETYPECODES.[Departure], .Translation = "Departure"})
        _departuretypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DEPARTURETYPECODES)) With {.Value = DEPARTURETYPECODES.[Completion], .Translation = "Completion"})
        _departuretypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DEPARTURETYPECODES)) With {.Value = DEPARTURETYPECODES.[Administrative], .Translation = "Administrative"})
        Me.Fields.Add(_departuretypecode)
        '
        '_receivedfarewelllettercode
        '
        _receivedfarewelllettercode.Name = "RECEIVEDFAREWELLLETTERCODE"
        _receivedfarewelllettercode.Caption = "Received farewell letter"
        _receivedfarewelllettercode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES)) With {.Value = RECEIVEDFAREWELLLETTERCODES.[No], .Translation = "No"})
        _receivedfarewelllettercode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES)) With {.Value = RECEIVEDFAREWELLLETTERCODES.[Yes], .Translation = "Yes"})
        _receivedfarewelllettercode.Value = RECEIVEDFAREWELLLETTERCODES.[No]
        Me.Fields.Add(_receivedfarewelllettercode)
        '
        '_dateformcompleted
        '
        _dateformcompleted.Name = "DATEFORMCOMPLETED"
        _dateformcompleted.Caption = "Form Completed Date"
        Me.Fields.Add(_dateformcompleted)
        '
        '_formcompletedby
        '
        _formcompletedby.Name = "FORMCOMPLETEDBY"
        _formcompletedby.Caption = "Form Completed By"
        _formcompletedby.MaxLength = 50
        Me.Fields.Add(_formcompletedby)
        '
        '_dateofdeparture
        '
        _dateofdeparture.Name = "DATEOFDEPARTURE"
        _dateofdeparture.Caption = "Date of the departure or program completion"
        Me.Fields.Add(_dateofdeparture)
        '
        '_dateprocessed
        '
        _dateprocessed.Name = "DATEPROCESSED"
        _dateprocessed.Caption = "Date processed"
        _dateprocessed.Visible = False
        Me.Fields.Add(_dateprocessed)
        '
        '_administrativecodeid
        '
        _administrativecodeid.Name = "ADMINISTRATIVECODEID"
        _administrativecodeid.Caption = "Administrative"
        _administrativecodeid.CodeTableName = "USR_DEPARTURE_ADMINISTRATIVE_CODE"
        Me.Fields.Add(_administrativecodeid)
        '
        '_administrativeexplanation
        '
        _administrativeexplanation.Name = "ADMINISTRATIVEEXPLANATION"
        _administrativeexplanation.Caption = "Explanation"
        _administrativeexplanation.MaxLength = 50
        Me.Fields.Add(_administrativeexplanation)
        '
        '_isdeparture
        '
        _isdeparture.Name = "ISDEPARTURE"
        _isdeparture.Caption = "Is Departure"
        Me.Fields.Add(_isdeparture)
        '
        '_isprogramcompletion
        '
        _isprogramcompletion.Name = "ISPROGRAMCOMPLETION"
        _isprogramcompletion.Caption = "Completed Program"
        Me.Fields.Add(_isprogramcompletion)
        '
        '_departureliveswithrelatives
        '
        _departureliveswithrelatives.Name = "DEPARTURE_LIVESWITHRELATIVES"
        _departureliveswithrelatives.Caption = "Gone to live with relatives"
        Me.Fields.Add(_departureliveswithrelatives)
        '
        '_departurefamilymoved
        '
        _departurefamilymoved.Name = "DEPARTURE_FAMILYMOVED"
        _departurefamilymoved.Caption = "Moved from project area"
        Me.Fields.Add(_departurefamilymoved)
        '
        '_departurefamilynowprovides
        '
        _departurefamilynowprovides.Name = "DEPARTURE_FAMILYNOWPROVIDES"
        _departurefamilynowprovides.Caption = "Family provides for child"
        Me.Fields.Add(_departurefamilynowprovides)
        '
        '_departureprojecttoofar
        '
        _departureprojecttoofar.Name = "DEPARTURE_PROJECTTOOFAR"
        _departureprojecttoofar.Caption = "Too far for the child to attend"
        Me.Fields.Add(_departureprojecttoofar)
        '
        '_departureremovedbyparents
        '
        _departureremovedbyparents.Name = "DEPARTURE_REMOVEDBYPARENTS"
        _departureremovedbyparents.Caption = "Removed by parents"
        Me.Fields.Add(_departureremovedbyparents)
        '
        '_departurelackofinterest
        '
        _departurelackofinterest.Name = "DEPARTURE_LACKOFINTEREST"
        _departurelackofinterest.Caption = "Lack of interest or commitment"
        Me.Fields.Add(_departurelackofinterest)
        '
        '_departureneededathome
        '
        _departureneededathome.Name = "DEPARTURE_NEEDEDATHOME"
        _departureneededathome.Caption = "Need at home to help family"
        Me.Fields.Add(_departureneededathome)
        '
        '_departureemployed
        '
        _departureemployed.Name = "DEPARTURE_EMPLOYED"
        _departureemployed.Caption = "Employed to help family"
        Me.Fields.Add(_departureemployed)
        '
        '_departuretransferred
        '
        _departuretransferred.Name = "DEPARTURE_TRANSFERRED"
        _departuretransferred.Caption = "Transferred to a different school"
        Me.Fields.Add(_departuretransferred)
        '
        '_departurefailed
        '
        _departurefailed.Name = "DEPARTURE_FAILED"
        _departurefailed.Caption = "Failed school courses"
        Me.Fields.Add(_departurefailed)
        '
        '_departuredeathofchild
        '
        _departuredeathofchild.Name = "DEPARTURE_DEATHOFCHILD"
        _departuredeathofchild.Caption = "Death of Child"
        Me.Fields.Add(_departuredeathofchild)
        '
        '_departureillness
        '
        _departureillness.Name = "DEPARTURE_ILLNESS"
        _departureillness.Caption = "Illness"
        Me.Fields.Add(_departureillness)
        '
        '_departurepregnancy
        '
        _departurepregnancy.Name = "DEPARTURE_PREGNANCY"
        _departurepregnancy.Caption = "Pregnancy"
        Me.Fields.Add(_departurepregnancy)
        '
        '_departuremarried
        '
        _departuremarried.Name = "DEPARTURE_MARRIED"
        _departuremarried.Caption = "Married"
        Me.Fields.Add(_departuremarried)
        '
        '_departureother
        '
        _departureother.Name = "DEPARTURE_OTHER"
        _departureother.Caption = "Other Departure Reason"
        _departureother.MaxLength = 250
        _departureother.MultiLine = True
        Me.Fields.Add(_departureother)
        '
        '_detailedexplanation
        '
        _detailedexplanation.Name = "DETAILEDEXPLANATION"
        _detailedexplanation.Caption = "Provide a detailed explanation of all departure reasons selected"
        _detailedexplanation.Required = False
        _detailedexplanation.MaxLength = 1000
        _detailedexplanation.MultiLine = True
        Me.Fields.Add(_detailedexplanation)
        '
        '_departurenewsituation
        '
        _departurenewsituation.Name = "DEPARTURENEWSITUATION"
        _departurenewsituation.Caption = "Provide a detailed explanation of the child's new situation, if known"
        _departurenewsituation.MaxLength = 1000
        _departurenewsituation.MultiLine = True
        Me.Fields.Add(_departurenewsituation)
        '
        '_programcompletionnewsituation
        '
        _programcompletionnewsituation.Name = "PROGRAMCOMPLETIONNEWSITUATION"
        _programcompletionnewsituation.Caption = "Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered"
        _programcompletionnewsituation.MaxLength = 1000
        _programcompletionnewsituation.MultiLine = True
        Me.Fields.Add(_programcompletionnewsituation)
        '
        '_ischildchristiancode
        '
        _ischildchristiancode.Name = "ISCHILDCHRISTIANCODE"
        _ischildchristiancode.Caption = "Child is a Christian"
        _ischildchristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[No], .Translation = "No"})
        _ischildchristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[Yes], .Translation = "Yes"})
        _ischildchristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[Unknown], .Translation = "Unknown"})
        _ischildchristiancode.Value = ISCHILDCHRISTIANCODES.[Unknown]
        Me.Fields.Add(_ischildchristiancode)
        '
        '_childchristiancomments
        '
        _childchristiancomments.Name = "CHILDCHRISTIANCOMMENTS"
        _childchristiancomments.Caption = "Comments"
        _childchristiancomments.MaxLength = 50
        Me.Fields.Add(_childchristiancomments)
        '
        '_didbecomechristiancode
        '
        _didbecomechristiancode.Name = "DIDBECOMECHRISTIANCODE"
        _didbecomechristiancode.Caption = "Child became a Christian while in the sponsorship program"
        _didbecomechristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[No], .Translation = "No"})
        _didbecomechristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[Yes], .Translation = "Yes"})
        _didbecomechristiancode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[Unknown], .Translation = "Unknown"})
        _didbecomechristiancode.Value = DIDBECOMECHRISTIANCODES.[Unknown]
        Me.Fields.Add(_didbecomechristiancode)
        '
        '_showschristianknowledge
        '
        _showschristianknowledge.Name = "SHOWSCHRISTIANKNOWLEDGE"
        _showschristianknowledge.Caption = "Child shows some knowledge of the Christian faith"
        Me.Fields.Add(_showschristianknowledge)
        '
        '_participateschristianactivities
        '
        _participateschristianactivities.Name = "PARTICIPATESCHRISTIANACTIVITIES"
        _participateschristianactivities.Caption = "Child sometimes participates in Christian activities, but does not lead those activities"
        Me.Fields.Add(_participateschristianactivities)
        '
        '_showschristianevidence
        '
        _showschristianevidence.Name = "SHOWSCHRISTIANEVIDENCE"
        _showschristianevidence.Caption = "Child shows some evidence of Christian faith and behavior"
        Me.Fields.Add(_showschristianevidence)
        '
        '_ownsbiblematerials
        '
        _ownsbiblematerials.Name = "OWNSBIBLEMATERIALS"
        _ownsbiblematerials.Caption = "Child has Scripture materials"
        Me.Fields.Add(_ownsbiblematerials)
        '
        '_childchristianexperience
        '
        _childchristianexperience.Name = "CHILDCHRISTIANEXPERIENCE"
        _childchristianexperience.Caption = "Provide a detailed explanation of the child's Christian experience"
        _childchristianexperience.MaxLength = 1000
        _childchristianexperience.MultiLine = True
        Me.Fields.Add(_childchristianexperience)
        '
        '_healthconditions
        '
        _healthconditions.Name = "HEALTHCONDITIONS"
        _healthconditions.Caption = "Note any illnesses the child had during their participaton in the program as well as what the child's current health is"
        _healthconditions.MaxLength = 1000
        _healthconditions.MultiLine = True
        _healthconditions.AllowZoom = True
        Me.Fields.Add(_healthconditions)
        '
        '_childmaturedcode
        '
        _childmaturedcode.Name = "CHILDMATUREDCODE"
        _childmaturedcode.Caption = "Child has matured appropriately for their age"
        _childmaturedcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of CHILDMATUREDCODES)) With {.Value = CHILDMATUREDCODES.[No], .Translation = "No"})
        _childmaturedcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of CHILDMATUREDCODES)) With {.Value = CHILDMATUREDCODES.[Yes], .Translation = "Yes"})
        _childmaturedcode.Value = CHILDMATUREDCODES.[No]
        Me.Fields.Add(_childmaturedcode)
        '
        '_levelofmaturity
        '
        _levelofmaturity.Name = "LEVELOFMATURITY"
        _levelofmaturity.Caption = "Provide a brief explanation of the chlid's level of maturity and how they relate to others around them"
        _levelofmaturity.MaxLength = 1000
        _levelofmaturity.MultiLine = True
        _levelofmaturity.AllowZoom = True
        Me.Fields.Add(_levelofmaturity)
        '
        '_highestclasslevelcodeid
        '
        _highestclasslevelcodeid.Name = "HIGHESTCLASSLEVELCODEID"
        _highestclasslevelcodeid.Caption = "Highest Class Level Completed"
        _highestclasslevelcodeid.CodeTableName = "USR_CHILDCLASSLEVEL_CODE"
        Me.Fields.Add(_highestclasslevelcodeid)
        '
        '_highestclasslevelother
        '
        _highestclasslevelother.Name = "HIGHESTCLASSLEVELOTHER"
        _highestclasslevelother.Caption = "Other"
        _highestclasslevelother.MaxLength = 20
        Me.Fields.Add(_highestclasslevelother)
        '
        '_courseofstudy
        '
        _courseofstudy.Name = "COURSEOFSTUDY"
        _courseofstudy.Caption = "Course of Study"
        _courseofstudy.MaxLength = 50
        Me.Fields.Add(_courseofstudy)
        '
        '_skillsbasicliteracy
        '
        _skillsbasicliteracy.Name = "SKILLS_BASICLITERACY"
        _skillsbasicliteracy.Caption = "Basic Literacy"
        Me.Fields.Add(_skillsbasicliteracy)
        '
        '_skillsbasicnumeracy
        '
        _skillsbasicnumeracy.Name = "SKILLS_BASICNUMERACY"
        _skillsbasicnumeracy.Caption = "Basic Numeracy"
        Me.Fields.Add(_skillsbasicnumeracy)
        '
        '_skillsthinkingproblemsolving
        '
        _skillsthinkingproblemsolving.Name = "SKILLS_THINKINGPROBLEMSOLVING"
        _skillsthinkingproblemsolving.Caption = "Thinking and problem-solving skills"
        Me.Fields.Add(_skillsthinkingproblemsolving)
        '
        '_skillsselfhelp
        '
        _skillsselfhelp.Name = "SKILLS_SELFHELP"
        _skillsselfhelp.Caption = "Self-help Skills"
        Me.Fields.Add(_skillsselfhelp)
        '
        '_skillsbusiness
        '
        _skillsbusiness.Name = "SKILLS_BUSINESS"
        _skillsbusiness.Caption = "Entrepreneurial (business) skills"
        Me.Fields.Add(_skillsbusiness)
        '
        '_skillslife
        '
        _skillslife.Name = "SKILLS_LIFE"
        _skillslife.Caption = "Life Skills"
        Me.Fields.Add(_skillslife)
        '
        '_skillsvocationaltechnical
        '
        _skillsvocationaltechnical.Name = "SKILLS_VOCATIONALTECHNICAL"
        _skillsvocationaltechnical.Caption = "Vocational and Technical Skills"
        Me.Fields.Add(_skillsvocationaltechnical)
        '
        '_skillsother
        '
        _skillsother.Name = "SKILLS_OTHER"
        _skillsother.Caption = "Other Skills"
        _skillsother.MaxLength = 50
        Me.Fields.Add(_skillsother)
        '
        '_generalcomments
        '
        _generalcomments.Name = "GENERALCOMMENTS"
        _generalcomments.Caption = "Summarize the project's overall impact on the child's life and provide any additional comments"
        _generalcomments.MaxLength = 1000
        _generalcomments.MultiLine = True
        _generalcomments.AllowZoom = True
        Me.Fields.Add(_generalcomments)
        '
        '_generalinfogroup
        '
        _generalinfogroup.Name = "GENERAL_INFO_GROUP"
        _generalinfogroup.Caption = "General Information"
        _generalinfogroup.Fields.Add("NODEPARTUREFORM")
        _generalinfogroup.Fields.Add("RECEIVEDFAREWELLLETTERCODE")
        _generalinfogroup.Fields.Add("DATEFORMCOMPLETED")
        _generalinfogroup.Fields.Add("FORMCOMPLETEDBY")
        _generalinfogroup.Fields.Add("DATEOFDEPARTURE")
        _generalinfogroup.Fields.Add("ADMINISTRATIVECODEID")
        _generalinfogroup.Fields.Add("ADMINISTRATIVEEXPLANATION")
        _generalinfogroup.Fields.Add("ISDEPARTURE")
        Me.Fields.Add(_generalinfogroup)
        '
        '_departurereasonstab
        '
        _departurereasonstab.Name = "DEPARTURE_REASONS_TAB"
        _departurereasonstab.Caption = "Reason for Departure"
        Me.Fields.Add(_departurereasonstab)
        '
        '_spiritualphysicaltab
        '
        _spiritualphysicaltab.Name = "SPIRITUAL_PHYSICAL_TAB"
        _spiritualphysicaltab.Caption = "Spiritual and Physical Impact"
        Me.Fields.Add(_spiritualphysicaltab)
        '
        '_socialcognitivetab
        '
        _socialcognitivetab.Name = "SOCIAL_COGNITIVE_TAB"
        _socialcognitivetab.Caption = "Social and Cognitive Imapct"
        Me.Fields.Add(_socialcognitivetab)
        '
        '_commentstab
        '
        _commentstab.Name = "COMMENTS_TAB"
        _commentstab.Caption = "General Comments"
        Me.Fields.Add(_commentstab)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Sponsorshipopportunitychild
    ''' </summary>
    <System.ComponentModel.Description("Sponsorshipopportunitychild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipopportunitychildid
        End Get
    End Property

    ''' <summary>
    ''' No Departure Form
    ''' </summary>
    <System.ComponentModel.Description("No Departure Form")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NODEPARTUREFORM]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _nodepartureform
        End Get
    End Property

    ''' <summary>
    ''' Type of Departure
    ''' </summary>
    <System.ComponentModel.Description("Type of Departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURETYPECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DEPARTURETYPECODES))
        Get
            Return _departuretypecode
        End Get
    End Property


    ''' <summary>
    ''' Received farewell letter
    ''' </summary>
    <System.ComponentModel.Description("Received farewell letter")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RECEIVEDFAREWELLLETTERCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES))
        Get
            Return _receivedfarewelllettercode
        End Get
    End Property

    ''' <summary>
    ''' Form Completed Date
    ''' </summary>
    <System.ComponentModel.Description("Form Completed Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEFORMCOMPLETED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateformcompleted
        End Get
    End Property

    ''' <summary>
    ''' Form Completed By
    ''' </summary>
    <System.ComponentModel.Description("Form Completed By")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FORMCOMPLETEDBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _formcompletedby
        End Get
    End Property

    ''' <summary>
    ''' Date of the departure or program completion
    ''' </summary>
    <System.ComponentModel.Description("Date of the departure or program completion")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEOFDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateofdeparture
        End Get
    End Property

    ''' <summary>
    ''' Date processed
    ''' </summary>
    <System.ComponentModel.Description("Date processed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEPROCESSED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateprocessed
        End Get
    End Property

    ''' <summary>
    ''' Administrative
    ''' </summary>
    <System.ComponentModel.Description("Administrative")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADMINISTRATIVECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _administrativecodeid
        End Get
    End Property

    ''' <summary>
    ''' Explanation
    ''' </summary>
    <System.ComponentModel.Description("Explanation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADMINISTRATIVEEXPLANATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _administrativeexplanation
        End Get
    End Property

    ''' <summary>
    ''' Is Departure
    ''' </summary>
    <System.ComponentModel.Description("Is Departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isdeparture
        End Get
    End Property

    ''' <summary>
    ''' Is Program Completion
    ''' </summary>
    <System.ComponentModel.Description("Completed Program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISPROGRAMCOMPLETION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isprogramcompletion
        End Get
    End Property

    ''' <summary>
    ''' Gone to live with relatives
    ''' </summary>
    <System.ComponentModel.Description("Gone to live with relatives")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_LIVESWITHRELATIVES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureliveswithrelatives
        End Get
    End Property

    ''' <summary>
    ''' Moved from project area
    ''' </summary>
    <System.ComponentModel.Description("Moved from project area")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAMILYMOVED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefamilymoved
        End Get
    End Property

    ''' <summary>
    ''' Family provides for child
    ''' </summary>
    <System.ComponentModel.Description("Family provides for child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAMILYNOWPROVIDES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefamilynowprovides
        End Get
    End Property

    ''' <summary>
    ''' Too far for the child to attend
    ''' </summary>
    <System.ComponentModel.Description("Too far for the child to attend")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_PROJECTTOOFAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureprojecttoofar
        End Get
    End Property

    ''' <summary>
    ''' Removed by parents
    ''' </summary>
    <System.ComponentModel.Description("Removed by parents")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_REMOVEDBYPARENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureremovedbyparents
        End Get
    End Property

    ''' <summary>
    ''' Lack of interest or commitment
    ''' </summary>
    <System.ComponentModel.Description("Lack of interest or commitment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_LACKOFINTEREST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurelackofinterest
        End Get
    End Property

    ''' <summary>
    ''' Need at home to help family
    ''' </summary>
    <System.ComponentModel.Description("Need at home to help family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_NEEDEDATHOME]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureneededathome
        End Get
    End Property

    ''' <summary>
    ''' Employed to help family
    ''' </summary>
    <System.ComponentModel.Description("Employed to help family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_EMPLOYED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureemployed
        End Get
    End Property

    ''' <summary>
    ''' Transferred to a different school
    ''' </summary>
    <System.ComponentModel.Description("Transferred to a different school")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_TRANSFERRED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuretransferred
        End Get
    End Property

    ''' <summary>
    ''' Failed school courses
    ''' </summary>
    <System.ComponentModel.Description("Failed school courses")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAILED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefailed
        End Get
    End Property

    ''' <summary>
    ''' Death of Child
    ''' </summary>
    <System.ComponentModel.Description("Death of Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_DEATHOFCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuredeathofchild
        End Get
    End Property

    ''' <summary>
    ''' Illness
    ''' </summary>
    <System.ComponentModel.Description("Illness")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_ILLNESS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureillness
        End Get
    End Property

    ''' <summary>
    ''' Pregnancy
    ''' </summary>
    <System.ComponentModel.Description("Pregnancy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_PREGNANCY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurepregnancy
        End Get
    End Property

    ''' <summary>
    ''' Married
    ''' </summary>
    <System.ComponentModel.Description("Married")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_MARRIED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuremarried
        End Get
    End Property

    ''' <summary>
    ''' Other Departure Reason
    ''' </summary>
    <System.ComponentModel.Description("Other Departure Reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_OTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departureother
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of all departure reasons selected
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of all departure reasons selected")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DETAILEDEXPLANATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _detailedexplanation
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's new situation, if known
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's new situation, if known")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURENEWSITUATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departurenewsituation
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PROGRAMCOMPLETIONNEWSITUATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _programcompletionnewsituation
        End Get
    End Property

    ''' <summary>
    ''' Child is a Christian
    ''' </summary>
    <System.ComponentModel.Description("Child is a Christian")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISCHILDCHRISTIANCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ISCHILDCHRISTIANCODES))
        Get
            Return _ischildchristiancode
        End Get
    End Property

    ''' <summary>
    ''' Comments
    ''' </summary>
    <System.ComponentModel.Description("Comments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCHRISTIANCOMMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childchristiancomments
        End Get
    End Property

    ''' <summary>
    ''' Child became a Christian while in the sponsorship program
    ''' </summary>
    <System.ComponentModel.Description("Child became a Christian while in the sponsorship program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DIDBECOMECHRISTIANCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DIDBECOMECHRISTIANCODES))
        Get
            Return _didbecomechristiancode
        End Get
    End Property

    ''' <summary>
    ''' Child shows some knowledge of the Christian faith
    ''' </summary>
    <System.ComponentModel.Description("Child shows some knowledge of the Christian faith")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SHOWSCHRISTIANKNOWLEDGE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showschristianknowledge
        End Get
    End Property

    ''' <summary>
    ''' Child sometimes participates in Christian activities, but does not lead those activities
    ''' </summary>
    <System.ComponentModel.Description("Child sometimes participates in Christian activities, but does not lead those activities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PARTICIPATESCHRISTIANACTIVITIES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participateschristianactivities
        End Get
    End Property

    ''' <summary>
    ''' Child shows some evidence of Christian faith and behavior
    ''' </summary>
    <System.ComponentModel.Description("Child shows some evidence of Christian faith and behavior")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SHOWSCHRISTIANEVIDENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showschristianevidence
        End Get
    End Property

    ''' <summary>
    ''' Child has Scripture materials
    ''' </summary>
    <System.ComponentModel.Description("Child has Scripture materials")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [OWNSBIBLEMATERIALS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _ownsbiblematerials
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's Christian experience
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's Christian experience")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCHRISTIANEXPERIENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childchristianexperience
        End Get
    End Property

    ''' <summary>
    ''' Note any illnesses the child had during their participaton in the program as well as what the child's current health is
    ''' </summary>
    <System.ComponentModel.Description("Note any illnesses the child had during their participaton in the program as well as what the child's current health is")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HEALTHCONDITIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _healthconditions
        End Get
    End Property

    ''' <summary>
    ''' Child has matured appropriately for their age
    ''' </summary>
    <System.ComponentModel.Description("Child has matured appropriately for their age")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDMATUREDCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of CHILDMATUREDCODES))
        Get
            Return _childmaturedcode
        End Get
    End Property

    ''' <summary>
    ''' Provide a brief explanation of the chlid's level of maturity and how they relate to others around them
    ''' </summary>
    <System.ComponentModel.Description("Provide a brief explanation of the chlid's level of maturity and how they relate to others around them")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [LEVELOFMATURITY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _levelofmaturity
        End Get
    End Property

    ''' <summary>
    ''' Highest Class Level Completed
    ''' </summary>
    <System.ComponentModel.Description("Highest Class Level Completed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTCLASSLEVELCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _highestclasslevelcodeid
        End Get
    End Property

    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HIGHESTCLASSLEVELOTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _highestclasslevelother
        End Get
    End Property

    ''' <summary>
    ''' Course of Study
    ''' </summary>
    <System.ComponentModel.Description("Course of Study")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COURSEOFSTUDY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _courseofstudy
        End Get
    End Property

    ''' <summary>
    ''' Basic Literacy
    ''' </summary>
    <System.ComponentModel.Description("Basic Literacy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_BASICLITERACY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsbasicliteracy
        End Get
    End Property

    ''' <summary>
    ''' Basic Numeracy
    ''' </summary>
    <System.ComponentModel.Description("Basic Numeracy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_BASICNUMERACY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsbasicnumeracy
        End Get
    End Property

    ''' <summary>
    ''' Thinking and problem-solving skills
    ''' </summary>
    <System.ComponentModel.Description("Thinking and problem-solving skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_THINKINGPROBLEMSOLVING]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsthinkingproblemsolving
        End Get
    End Property

    ''' <summary>
    ''' Self-help Skills
    ''' </summary>
    <System.ComponentModel.Description("Self-help Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_SELFHELP]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsselfhelp
        End Get
    End Property

    ''' <summary>
    ''' Entrepreneurial (business) skills
    ''' </summary>
    <System.ComponentModel.Description("Entrepreneurial (business) skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_BUSINESS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsbusiness
        End Get
    End Property

    ''' <summary>
    ''' Life Skills
    ''' </summary>
    <System.ComponentModel.Description("Life Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_LIFE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillslife
        End Get
    End Property

    ''' <summary>
    ''' Vocational and Technical Skills
    ''' </summary>
    <System.ComponentModel.Description("Vocational and Technical Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_VOCATIONALTECHNICAL]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _skillsvocationaltechnical
        End Get
    End Property

    ''' <summary>
    ''' Other Skills
    ''' </summary>
    <System.ComponentModel.Description("Other Skills")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SKILLS_OTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _skillsother
        End Get
    End Property

    ''' <summary>
    ''' Summarize the project's overall impact on the child's life and provide any additional comments
    ''' </summary>
    <System.ComponentModel.Description("Summarize the project's overall impact on the child's life and provide any additional comments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GENERALCOMMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _generalcomments
        End Get
    End Property

    ''' <summary>
    ''' General Information
    ''' </summary>
    <System.ComponentModel.Description("General Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GENERAL_INFO_GROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _generalinfogroup
        End Get
    End Property

    ''' <summary>
    ''' Reason for Departure
    ''' </summary>
    <System.ComponentModel.Description("Reason for Departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_REASONS_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _departurereasonstab
        End Get
    End Property

    ''' <summary>
    ''' Spiritual and Physical Impact
    ''' </summary>
    <System.ComponentModel.Description("Spiritual and Physical Impact")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPIRITUAL_PHYSICAL_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _spiritualphysicaltab
        End Get
    End Property

    ''' <summary>
    ''' Social and Cognitive Imapct
    ''' </summary>
    <System.ComponentModel.Description("Social and Cognitive Imapct")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SOCIAL_COGNITIVE_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _socialcognitivetab
        End Get
    End Property

    ''' <summary>
    ''' General Comments
    ''' </summary>
    <System.ComponentModel.Description("General Comments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [COMMENTS_TAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _commentstab
        End Get
    End Property

End Class
