Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture Reason for Departure Tab View' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "1d4a806b-90b7-45b5-81bb-0b9a72247804", "0e3ce299-26d8-4c99-b7c2-f1a178c99bab", "ChildDeparture")> _
Partial Public Class [ChildDepartureReasonForDepartureTabViewUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _departuretype As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _dateformcompleted As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _formcompletedby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _dateofdeparture As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _dateprocessed As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _isdeparture As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _isprogramcompletion As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureliveswithrelatives As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefamilymoved As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefamilynowprovides As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureprojecttoofar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureremovedbyparents As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurelackofinterest As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureneededathome As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureemployed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuretransferred As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefailed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuredeathofchild As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureillness As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurepregnancy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuremarried As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _detailedexplanation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _departurenewsituation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _programcompletionnewsituation As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _departuretype = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _dateformcompleted = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _formcompletedby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _dateofdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _dateprocessed = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _isdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _isprogramcompletion = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureliveswithrelatives = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefamilymoved = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefamilynowprovides = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureprojecttoofar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureremovedbyparents = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurelackofinterest = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureneededathome = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureemployed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuretransferred = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefailed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuredeathofchild = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureillness = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurepregnancy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuremarried = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _detailedexplanation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _departurenewsituation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _programcompletionnewsituation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("1d4a806b-90b7-45b5-81bb-0b9a72247804")
        MyBase.DataFormInstanceId = New Guid("0e3ce299-26d8-4c99-b7c2-f1a178c99bab")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureReasonForDepartureTabView.html"

        '
        '_departuretype
        '
        _departuretype.Name = "DEPARTURETYPE"
        _departuretype.Caption = "Type of departure"
        _departuretype.DBReadOnly = True
        Me.Fields.Add(_departuretype)
        '
        '_dateformcompleted
        '
        _dateformcompleted.Name = "DATEFORMCOMPLETED"
        _dateformcompleted.Caption = "Form Completed Date"
        _dateformcompleted.DBReadOnly = True
        Me.Fields.Add(_dateformcompleted)
        '
        '_formcompletedby
        '
        _formcompletedby.Name = "FORMCOMPLETEDBY"
        _formcompletedby.Caption = "Form Completed By"
        _formcompletedby.DBReadOnly = True
        _formcompletedby.MaxLength = 50
        Me.Fields.Add(_formcompletedby)
        '
        '_dateofdeparture
        '
        _dateofdeparture.Name = "DATEOFDEPARTURE"
        _dateofdeparture.Caption = "Date of the departure or program completion"
        _dateofdeparture.DBReadOnly = True
        Me.Fields.Add(_dateofdeparture)
        '
        '_dateprocessed
        '
        _dateprocessed.Name = "DATEPROCESSED"
        _dateprocessed.Caption = "Date processed"
        _dateprocessed.Visible = False
        _dateprocessed.DBReadOnly = True
        Me.Fields.Add(_dateprocessed)
        '
        '_isdeparture
        '
        _isdeparture.Name = "ISDEPARTURE"
        _isdeparture.Caption = "Is Departure"
        _isdeparture.DBReadOnly = True
        Me.Fields.Add(_isdeparture)
        '
        '_isprogramcompletion
        '
        _isprogramcompletion.Name = "ISPROGRAMCOMPLETION"
        _isprogramcompletion.Caption = "Completed Program"
        _isprogramcompletion.DBReadOnly = True
        Me.Fields.Add(_isprogramcompletion)
        '
        '_departureliveswithrelatives
        '
        _departureliveswithrelatives.Name = "DEPARTURE_LIVESWITHRELATIVES"
        _departureliveswithrelatives.Caption = "Gone to live with relatives"
        _departureliveswithrelatives.DBReadOnly = True
        Me.Fields.Add(_departureliveswithrelatives)
        '
        '_departurefamilymoved
        '
        _departurefamilymoved.Name = "DEPARTURE_FAMILYMOVED"
        _departurefamilymoved.Caption = "Moved from project area"
        _departurefamilymoved.DBReadOnly = True
        Me.Fields.Add(_departurefamilymoved)
        '
        '_departurefamilynowprovides
        '
        _departurefamilynowprovides.Name = "DEPARTURE_FAMILYNOWPROVIDES"
        _departurefamilynowprovides.Caption = "Family provides for child"
        _departurefamilynowprovides.DBReadOnly = True
        Me.Fields.Add(_departurefamilynowprovides)
        '
        '_departureprojecttoofar
        '
        _departureprojecttoofar.Name = "DEPARTURE_PROJECTTOOFAR"
        _departureprojecttoofar.Caption = "Too far for the child to attend"
        _departureprojecttoofar.DBReadOnly = True
        Me.Fields.Add(_departureprojecttoofar)
        '
        '_departureremovedbyparents
        '
        _departureremovedbyparents.Name = "DEPARTURE_REMOVEDBYPARENTS"
        _departureremovedbyparents.Caption = "Removed by parents"
        _departureremovedbyparents.DBReadOnly = True
        Me.Fields.Add(_departureremovedbyparents)
        '
        '_departurelackofinterest
        '
        _departurelackofinterest.Name = "DEPARTURE_LACKOFINTEREST"
        _departurelackofinterest.Caption = "Lack of interest or commitment"
        _departurelackofinterest.DBReadOnly = True
        Me.Fields.Add(_departurelackofinterest)
        '
        '_departureneededathome
        '
        _departureneededathome.Name = "DEPARTURE_NEEDEDATHOME"
        _departureneededathome.Caption = "Need at home to help family"
        _departureneededathome.DBReadOnly = True
        Me.Fields.Add(_departureneededathome)
        '
        '_departureemployed
        '
        _departureemployed.Name = "DEPARTURE_EMPLOYED"
        _departureemployed.Caption = "Employed to help family"
        _departureemployed.DBReadOnly = True
        Me.Fields.Add(_departureemployed)
        '
        '_departuretransferred
        '
        _departuretransferred.Name = "DEPARTURE_TRANSFERRED"
        _departuretransferred.Caption = "Transferred to a different school"
        _departuretransferred.DBReadOnly = True
        Me.Fields.Add(_departuretransferred)
        '
        '_departurefailed
        '
        _departurefailed.Name = "DEPARTURE_FAILED"
        _departurefailed.Caption = "Failed school courses"
        _departurefailed.DBReadOnly = True
        Me.Fields.Add(_departurefailed)
        '
        '_departuredeathofchild
        '
        _departuredeathofchild.Name = "DEPARTURE_DEATHOFCHILD"
        _departuredeathofchild.Caption = "Death of Child"
        _departuredeathofchild.DBReadOnly = True
        Me.Fields.Add(_departuredeathofchild)
        '
        '_departureillness
        '
        _departureillness.Name = "DEPARTURE_ILLNESS"
        _departureillness.Caption = "Illness"
        _departureillness.DBReadOnly = True
        Me.Fields.Add(_departureillness)
        '
        '_departurepregnancy
        '
        _departurepregnancy.Name = "DEPARTURE_PREGNANCY"
        _departurepregnancy.Caption = "Pregnancy"
        _departurepregnancy.DBReadOnly = True
        Me.Fields.Add(_departurepregnancy)
        '
        '_departuremarried
        '
        _departuremarried.Name = "DEPARTURE_MARRIED"
        _departuremarried.Caption = "Married"
        _departuremarried.DBReadOnly = True
        Me.Fields.Add(_departuremarried)
        '
        '_departureother
        '
        _departureother.Name = "DEPARTURE_OTHER"
        _departureother.Caption = "Other Departure Reason"
        _departureother.DBReadOnly = True
        _departureother.MaxLength = 250
        _departureother.MultiLine = True
        Me.Fields.Add(_departureother)
        '
        '_detailedexplanation
        '
        _detailedexplanation.Name = "DETAILEDEXPLANATION"
        _detailedexplanation.Caption = "Provide a detailed explanation of all departure reasons selected"
        _detailedexplanation.DBReadOnly = True
        _detailedexplanation.MaxLength = 1000
        _detailedexplanation.MultiLine = True
        Me.Fields.Add(_detailedexplanation)
        '
        '_departurenewsituation
        '
        _departurenewsituation.Name = "DEPARTURENEWSITUATION"
        _departurenewsituation.Caption = "Provide a detailed explanation of the child's new situation, if known"
        _departurenewsituation.DBReadOnly = True
        _departurenewsituation.MaxLength = 1000
        _departurenewsituation.MultiLine = True
        Me.Fields.Add(_departurenewsituation)
        '
        '_programcompletionnewsituation
        '
        _programcompletionnewsituation.Name = "PROGRAMCOMPLETIONNEWSITUATION"
        _programcompletionnewsituation.Caption = "Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered"
        _programcompletionnewsituation.DBReadOnly = True
        _programcompletionnewsituation.MaxLength = 1000
        _programcompletionnewsituation.MultiLine = True
        Me.Fields.Add(_programcompletionnewsituation)

        OnCreated()

    End Sub

    '''
    ''' <summary>
    ''' Type of departure
    ''' </summary>
    <System.ComponentModel.Description("Type of departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURETYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departuretype
        End Get
    End Property

    ''' <summary>
    ''' Form Completed Date
    ''' </summary>
    <System.ComponentModel.Description("Form Completed Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEFORMCOMPLETED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateformcompleted
        End Get
    End Property

    ''' <summary>
    ''' Form Completed By
    ''' </summary>
    <System.ComponentModel.Description("Form Completed By")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FORMCOMPLETEDBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _formcompletedby
        End Get
    End Property

    ''' <summary>
    ''' Date of the departure or program completion
    ''' </summary>
    <System.ComponentModel.Description("Date of the departure or program completion")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEOFDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateofdeparture
        End Get
    End Property

    ''' <summary>
    ''' Date processed
    ''' </summary>
    <System.ComponentModel.Description("Date processed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEPROCESSED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateprocessed
        End Get
    End Property

    ''' <summary>
    ''' Is Departure
    ''' </summary>
    <System.ComponentModel.Description("Is Departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isdeparture
        End Get
    End Property

    ''' <summary>
    ''' Completed Program
    ''' </summary>
    <System.ComponentModel.Description("Completed Program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISPROGRAMCOMPLETION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isprogramcompletion
        End Get
    End Property

    ''' <summary>
    ''' Gone to live with relatives
    ''' </summary>
    <System.ComponentModel.Description("Gone to live with relatives")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_LIVESWITHRELATIVES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureliveswithrelatives
        End Get
    End Property

    ''' <summary>
    ''' Moved from project area
    ''' </summary>
    <System.ComponentModel.Description("Moved from project area")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAMILYMOVED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefamilymoved
        End Get
    End Property

    ''' <summary>
    ''' Family provides for child
    ''' </summary>
    <System.ComponentModel.Description("Family provides for child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAMILYNOWPROVIDES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefamilynowprovides
        End Get
    End Property

    ''' <summary>
    ''' Too far for the child to attend
    ''' </summary>
    <System.ComponentModel.Description("Too far for the child to attend")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_PROJECTTOOFAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureprojecttoofar
        End Get
    End Property

    ''' <summary>
    ''' Removed by parents
    ''' </summary>
    <System.ComponentModel.Description("Removed by parents")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_REMOVEDBYPARENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureremovedbyparents
        End Get
    End Property

    ''' <summary>
    ''' Lack of interest or commitment
    ''' </summary>
    <System.ComponentModel.Description("Lack of interest or commitment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_LACKOFINTEREST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurelackofinterest
        End Get
    End Property

    ''' <summary>
    ''' Need at home to help family
    ''' </summary>
    <System.ComponentModel.Description("Need at home to help family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_NEEDEDATHOME]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureneededathome
        End Get
    End Property

    ''' <summary>
    ''' Employed to help family
    ''' </summary>
    <System.ComponentModel.Description("Employed to help family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_EMPLOYED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureemployed
        End Get
    End Property

    ''' <summary>
    ''' Transferred to a different school
    ''' </summary>
    <System.ComponentModel.Description("Transferred to a different school")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_TRANSFERRED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuretransferred
        End Get
    End Property

    ''' <summary>
    ''' Failed school courses
    ''' </summary>
    <System.ComponentModel.Description("Failed school courses")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAILED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefailed
        End Get
    End Property

    ''' <summary>
    ''' Death of Child
    ''' </summary>
    <System.ComponentModel.Description("Death of Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_DEATHOFCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuredeathofchild
        End Get
    End Property

    ''' <summary>
    ''' Illness
    ''' </summary>
    <System.ComponentModel.Description("Illness")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_ILLNESS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureillness
        End Get
    End Property

    ''' <summary>
    ''' Pregnancy
    ''' </summary>
    <System.ComponentModel.Description("Pregnancy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_PREGNANCY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurepregnancy
        End Get
    End Property

    ''' <summary>
    ''' Married
    ''' </summary>
    <System.ComponentModel.Description("Married")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_MARRIED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuremarried
        End Get
    End Property

    ''' <summary>
    ''' Other Departure Reason
    ''' </summary>
    <System.ComponentModel.Description("Other Departure Reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_OTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departureother
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of all departure reasons selected
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of all departure reasons selected")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DETAILEDEXPLANATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _detailedexplanation
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's new situation, if known
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's new situation, if known")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURENEWSITUATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departurenewsituation
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PROGRAMCOMPLETIONNEWSITUATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _programcompletionnewsituation
        End Get
    End Property

End Class
