Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture Reason for Departure Tab Edit' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "2bd5152b-7763-428d-b131-185183ef434b", "d4f6b9ab-1167-4bcf-bac7-a4be916e264a", "ChildDeparture")> _
Partial Public Class [ChildDepartureReasonForDepartureTabEditUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    '   ''' <summary>
    '   ''' Enumerated values for use with the RECEIVEDFAREWELLLETTERCODE property
    '   ''' </summary>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    '   Public Enum RECEIVEDFAREWELLLETTERCODES As Integer
    '       [No] = 0
    '       [Yes] = 1
    '   End Enum

    ''' <summary>
    ''' Enumerated values for use with the DEPARTURETYPECODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum DEPARTURETYPECODES As Integer
        [Departure] = 0
        [Completion] = 1
        [Administrative] = 2
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _sponsorshipopportunitychildid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _departuretypecode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DEPARTURETYPECODES))
    'Private WithEvents _nodepartureform As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    'Private WithEvents _receivedfarewelllettercode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES))
    'Private WithEvents _dateformcompleted As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    'Private WithEvents _formcompletedby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    'Private WithEvents _dateofdeparture As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    'Private WithEvents _dateprocessed As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    'Private WithEvents _administrativecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    'Private WithEvents _administrativeexplanation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _isdeparture As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _isprogramcompletion As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureliveswithrelatives As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefamilymoved As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefamilynowprovides As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureprojecttoofar As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureremovedbyparents As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurelackofinterest As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureneededathome As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureemployed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuretransferred As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurefailed As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuredeathofchild As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureillness As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departurepregnancy As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departuremarried As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departureother As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _detailedexplanation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _departurenewsituation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _programcompletionnewsituation As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _sponsorshipopportunitychildid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _departuretypecode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DEPARTURETYPECODES))
        '_nodepartureform = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        '_receivedfarewelllettercode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES))
        '_dateformcompleted = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        '_formcompletedby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        '_dateofdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        '_dateprocessed = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        '_administrativecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        '_administrativeexplanation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _isdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _isprogramcompletion = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureliveswithrelatives = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefamilymoved = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefamilynowprovides = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureprojecttoofar = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureremovedbyparents = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurelackofinterest = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureneededathome = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureemployed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuretransferred = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurefailed = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuredeathofchild = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureillness = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departurepregnancy = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departuremarried = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departureother = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _detailedexplanation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _departurenewsituation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _programcompletionnewsituation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("2bd5152b-7763-428d-b131-185183ef434b")
        MyBase.DataFormInstanceId = New Guid("d4f6b9ab-1167-4bcf-bac7-a4be916e264a")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/ChildDepartureReasonForDepartureTabEdit.html"

        '
        '_sponsorshipopportunitychildid
        '
        _sponsorshipopportunitychildid.Name = "SPONSORSHIPOPPORTUNITYCHILDID"
        _sponsorshipopportunitychildid.Caption = "Sponsorshipopportunitychild"
        _sponsorshipopportunitychildid.Required = True
        _sponsorshipopportunitychildid.Visible = False
        Me.Fields.Add(_sponsorshipopportunitychildid)
        '
        '_departuretypecode
        '
        _departuretypecode.Name = "DEPARTURETYPECODE"
        _departuretypecode.Caption = "Type of departure"
        _departuretypecode.Required = True
        _departuretypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DEPARTURETYPECODES)) With {.Value = DEPARTURETYPECODES.[Departure], .Translation = "Departure"})
        _departuretypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DEPARTURETYPECODES)) With {.Value = DEPARTURETYPECODES.[Completion], .Translation = "Completion"})
        _departuretypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DEPARTURETYPECODES)) With {.Value = DEPARTURETYPECODES.[Administrative], .Translation = "Administrative"})
        Me.Fields.Add(_departuretypecode)


        ''
        ''_nodepartureform
        ''
        '_nodepartureform.Name = "NODEPARTUREFORM"
        '_nodepartureform.Caption = "No Departure Form"
        'Me.Fields.Add(_nodepartureform)
        ''
        ''_receivedfarewelllettercode
        ''
        '_receivedfarewelllettercode.Name = "RECEIVEDFAREWELLLETTERCODE"
        '_receivedfarewelllettercode.Caption = "Received farewell letter"
        '_receivedfarewelllettercode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES)) With {.Value = RECEIVEDFAREWELLLETTERCODES.[No], .Translation = "No"})
        '_receivedfarewelllettercode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES)) With {.Value = RECEIVEDFAREWELLLETTERCODES.[Yes], .Translation = "Yes"})
        '_receivedfarewelllettercode.Value = RECEIVEDFAREWELLLETTERCODES.[Yes]
        'Me.Fields.Add(_receivedfarewelllettercode)
        ''
        ''_dateformcompleted
        ''
        '_dateformcompleted.Name = "DATEFORMCOMPLETED"
        '_dateformcompleted.Caption = "Form Completed Date"
        'Me.Fields.Add(_dateformcompleted)
        ''
        ''_formcompletedby
        ''
        '_formcompletedby.Name = "FORMCOMPLETEDBY"
        '_formcompletedby.Caption = "Form Completed By"
        '_formcompletedby.MaxLength = 50
        'Me.Fields.Add(_formcompletedby)
        ''
        ''_dateofdeparture
        ''
        '_dateofdeparture.Name = DepartureFieldNames.DATEOFDEPARTURE.ToString()
        '_dateofdeparture.Caption = "Date of the departure or program completion"
        'Me.Fields.Add(_dateofdeparture)
        ''
        ''_dateprocessed
        ''
        '_dateprocessed.Name = DepartureFieldNames.DATEPROCESSED.ToString()
        '_dateprocessed.Caption = "Date processed"
        '_dateprocessed.Visible = False
        'Me.Fields.Add(_dateprocessed)
        ''
        ''_administrativecodeid
        ''
        '_administrativecodeid.Name = "ADMINISTRATIVECODEID"
        '_administrativecodeid.Caption = "Administrative"
        '_administrativecodeid.CodeTableName = "USR_DEPARTURE_ADMINISTRATIVE_CODE"
        'Me.Fields.Add(_administrativecodeid)
        ''
        ''_administrativeexplanation
        ''
        '_administrativeexplanation.Name = "ADMINISTRATIVEEXPLANATION"
        '_administrativeexplanation.Caption = "Explanation"
        '_administrativeexplanation.MaxLength = 50
        'Me.Fields.Add(_administrativeexplanation)
        '
        '_isdeparture
        '
        _isdeparture.Name = DepartureFieldNames.ISDEPARTURE.ToString()
        _isdeparture.Caption = "Is Departure"
        Me.Fields.Add(_isdeparture)
        '
        '_isprogramcompletion
        '
        _isprogramcompletion.Name = DepartureFieldNames.ISPROGRAMCOMPLETION.ToString()
        _isprogramcompletion.Caption = "Completed Program"
        Me.Fields.Add(_isprogramcompletion)
        '
        '_departureliveswithrelatives
        '
        _departureliveswithrelatives.Name = DepartureFieldNames.DEPARTURE_LIVESWITHRELATIVES.ToString()
        _departureliveswithrelatives.Caption = "Gone to live with relatives"
        Me.Fields.Add(_departureliveswithrelatives)
        '
        '_departurefamilymoved
        '
        _departurefamilymoved.Name = DepartureFieldNames.DEPARTURE_FAMILYMOVED.ToString()
        _departurefamilymoved.Caption = "Moved from project area"
        Me.Fields.Add(_departurefamilymoved)
        '
        '_departurefamilynowprovides
        '
        _departurefamilynowprovides.Name = DepartureFieldNames.DEPARTURE_FAMILYNOWPROVIDES.ToString()
        _departurefamilynowprovides.Caption = "Family provides for child"
        Me.Fields.Add(_departurefamilynowprovides)
        '
        '_departureprojecttoofar
        '
        _departureprojecttoofar.Name = DepartureFieldNames.DEPARTURE_PROJECTTOOFAR.ToString()
        _departureprojecttoofar.Caption = "Too far for the child to attend"
        Me.Fields.Add(_departureprojecttoofar)
        '
        '_departureremovedbyparents
        '
        _departureremovedbyparents.Name = DepartureFieldNames.DEPARTURE_REMOVEDBYPARENTS.ToString()
        _departureremovedbyparents.Caption = "Removed by parents"
        Me.Fields.Add(_departureremovedbyparents)
        '
        '_departurelackofinterest
        '
        _departurelackofinterest.Name = DepartureFieldNames.DEPARTURE_LACKOFINTEREST.ToString()
        _departurelackofinterest.Caption = "Lack of interest or commitment"
        Me.Fields.Add(_departurelackofinterest)
        '
        '_departureneededathome
        '
        _departureneededathome.Name = DepartureFieldNames.DEPARTURE_NEEDEDATHOME.ToString()
        _departureneededathome.Caption = "Need at home to help family"
        Me.Fields.Add(_departureneededathome)
        '
        '_departureemployed
        '
        _departureemployed.Name = DepartureFieldNames.DEPARTURE_EMPLOYED.ToString()
        _departureemployed.Caption = "Employed to help family"
        Me.Fields.Add(_departureemployed)
        '
        '_departuretransferred
        '
        _departuretransferred.Name = DepartureFieldNames.DEPARTURE_TRANSFERRED.ToString()
        _departuretransferred.Caption = "Transferred to a different school"
        Me.Fields.Add(_departuretransferred)
        '
        '_departurefailed
        '
        _departurefailed.Name = DepartureFieldNames.DEPARTURE_FAILED.ToString()
        _departurefailed.Caption = "Failed school courses"
        Me.Fields.Add(_departurefailed)
        '
        '_departuredeathofchild
        '
        _departuredeathofchild.Name = DepartureFieldNames.DEPARTURE_DEATHOFCHILD.ToString()
        _departuredeathofchild.Caption = "Death of Child"
        Me.Fields.Add(_departuredeathofchild)
        '
        '_departureillness
        '
        _departureillness.Name = DepartureFieldNames.DEPARTURE_ILLNESS.ToString()
        _departureillness.Caption = "Illness"
        Me.Fields.Add(_departureillness)
        '
        '_departurepregnancy
        '
        _departurepregnancy.Name = DepartureFieldNames.DEPARTURE_PREGNANCY.ToString()
        _departurepregnancy.Caption = "Pregnancy"
        Me.Fields.Add(_departurepregnancy)
        '
        '_departuremarried
        '
        _departuremarried.Name = DepartureFieldNames.DEPARTURE_MARRIED.ToString()
        _departuremarried.Caption = "Married"
        Me.Fields.Add(_departuremarried)
        '
        '_departureother
        '
        _departureother.Name = DepartureFieldNames.DEPARTURE_OTHER.ToString()
        _departureother.Caption = "Other Departure Reason"
        _departureother.MaxLength = 250
        _departureother.MultiLine = True
        Me.Fields.Add(_departureother)
        '
        '_detailedexplanation
        '
        _detailedexplanation.Name = DepartureFieldNames.DETAILEDEXPLANATION.ToString()
        _detailedexplanation.Caption = "Provide a detailed explanation of all departure reasons selected"
        _detailedexplanation.MaxLength = 1000
        _detailedexplanation.MultiLine = True
        Me.Fields.Add(_detailedexplanation)
        '
        '_departurenewsituation
        '
        _departurenewsituation.Name = DepartureFieldNames.DEPARTURENEWSITUATION.ToString()
        _departurenewsituation.Caption = "Provide a detailed explanation of the child's new situation, if known"
        _departurenewsituation.MaxLength = 1000
        _departurenewsituation.MultiLine = True
        Me.Fields.Add(_departurenewsituation)
        '
        '_programcompletionnewsituation
        '
        _programcompletionnewsituation.Name = DepartureFieldNames.PROGRAMCOMPLETIONNEWSITUATION.ToString()
        _programcompletionnewsituation.Caption = "Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered"
        _programcompletionnewsituation.MaxLength = 1000
        _programcompletionnewsituation.MultiLine = True
        Me.Fields.Add(_programcompletionnewsituation)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Sponsorshipopportunitychild
    ''' </summary>
    <System.ComponentModel.Description("Sponsorshipopportunitychild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _sponsorshipopportunitychildid
        End Get
    End Property

    ''' <summary>
    ''' Type of Departure
    ''' </summary>
    <System.ComponentModel.Description("Type of Departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURETYPECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of DEPARTURETYPECODES))
        Get
            Return _departuretypecode
        End Get
    End Property

    '''' <summary>
    '''' No Departure Form
    '''' </summary>
    '<System.ComponentModel.Description("No Departure Form")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [NODEPARTUREFORM]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    '    Get
    '        Return _nodepartureform
    '    End Get
    'End Property

    '''' <summary>
    '''' Received farewell letter
    '''' </summary>
    '<System.ComponentModel.Description("Received farewell letter")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [RECEIVEDFAREWELLLETTERCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES))
    '    Get
    '        Return _receivedfarewelllettercode
    '    End Get
    'End Property

    '''' <summary>
    '''' Form Completed Date
    '''' </summary>
    '<System.ComponentModel.Description("Form Completed Date")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [DATEFORMCOMPLETED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    '    Get
    '        Return _dateformcompleted
    '    End Get
    'End Property

    '''' <summary>
    '''' Form Completed By
    '''' </summary>
    '<System.ComponentModel.Description("Form Completed By")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [FORMCOMPLETEDBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    '    Get
    '        Return _formcompletedby
    '    End Get
    'End Property

    '''' <summary>
    '''' Date of the departure or program completion
    '''' </summary>
    '<System.ComponentModel.Description("Date of the departure or program completion")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [DATEOFDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    '    Get
    '        Return _dateofdeparture
    '    End Get
    'End Property

    '''' <summary>
    '''' Date processed
    '''' </summary>
    '<System.ComponentModel.Description("Date processed")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [DATEPROCESSED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    '    Get
    '        Return _dateprocessed
    '    End Get
    'End Property

    '''' <summary>
    '''' Administrative
    '''' </summary>
    '<System.ComponentModel.Description("Administrative")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [ADMINISTRATIVECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    '    Get
    '        Return _administrativecodeid
    '    End Get
    'End Property

    '''' <summary>
    '''' Explanation
    '''' </summary>
    '<System.ComponentModel.Description("Explanation")> _
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    'Public ReadOnly Property [ADMINISTRATIVEEXPLANATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    '    Get
    '        Return _administrativeexplanation
    '    End Get
    'End Property

    ''' <summary>
    ''' Is Departure
    ''' </summary>
    <System.ComponentModel.Description("Is Departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isdeparture
        End Get
    End Property

    ''' <summary>
    ''' Completed Program
    ''' </summary>
    <System.ComponentModel.Description("Completed Program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISPROGRAMCOMPLETION]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isprogramcompletion
        End Get
    End Property

    ''' <summary>
    ''' Gone to live with relatives
    ''' </summary>
    <System.ComponentModel.Description("Gone to live with relatives")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_LIVESWITHRELATIVES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureliveswithrelatives
        End Get
    End Property

    ''' <summary>
    ''' Moved from project area
    ''' </summary>
    <System.ComponentModel.Description("Moved from project area")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAMILYMOVED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefamilymoved
        End Get
    End Property

    ''' <summary>
    ''' Family provides for child
    ''' </summary>
    <System.ComponentModel.Description("Family provides for child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAMILYNOWPROVIDES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefamilynowprovides
        End Get
    End Property

    ''' <summary>
    ''' Too far for the child to attend
    ''' </summary>
    <System.ComponentModel.Description("Too far for the child to attend")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_PROJECTTOOFAR]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureprojecttoofar
        End Get
    End Property

    ''' <summary>
    ''' Removed by parents
    ''' </summary>
    <System.ComponentModel.Description("Removed by parents")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_REMOVEDBYPARENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureremovedbyparents
        End Get
    End Property

    ''' <summary>
    ''' Lack of interest or commitment
    ''' </summary>
    <System.ComponentModel.Description("Lack of interest or commitment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_LACKOFINTEREST]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurelackofinterest
        End Get
    End Property

    ''' <summary>
    ''' Need at home to help family
    ''' </summary>
    <System.ComponentModel.Description("Need at home to help family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_NEEDEDATHOME]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureneededathome
        End Get
    End Property

    ''' <summary>
    ''' Employed to help family
    ''' </summary>
    <System.ComponentModel.Description("Employed to help family")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_EMPLOYED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureemployed
        End Get
    End Property

    ''' <summary>
    ''' Transferred to a different school
    ''' </summary>
    <System.ComponentModel.Description("Transferred to a different school")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_TRANSFERRED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuretransferred
        End Get
    End Property

    ''' <summary>
    ''' Failed school courses
    ''' </summary>
    <System.ComponentModel.Description("Failed school courses")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_FAILED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurefailed
        End Get
    End Property

    ''' <summary>
    ''' Death of Child
    ''' </summary>
    <System.ComponentModel.Description("Death of Child")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_DEATHOFCHILD]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuredeathofchild
        End Get
    End Property

    ''' <summary>
    ''' Illness
    ''' </summary>
    <System.ComponentModel.Description("Illness")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_ILLNESS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departureillness
        End Get
    End Property

    ''' <summary>
    ''' Pregnancy
    ''' </summary>
    <System.ComponentModel.Description("Pregnancy")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_PREGNANCY]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departurepregnancy
        End Get
    End Property

    ''' <summary>
    ''' Married
    ''' </summary>
    <System.ComponentModel.Description("Married")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_MARRIED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _departuremarried
        End Get
    End Property

    ''' <summary>
    ''' Other Departure Reason
    ''' </summary>
    <System.ComponentModel.Description("Other Departure Reason")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURE_OTHER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departureother
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of all departure reasons selected
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of all departure reasons selected")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DETAILEDEXPLANATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _detailedexplanation
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's new situation, if known
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's new situation, if known")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURENEWSITUATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departurenewsituation
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's new situation which will occur following the child's satisfactory completion of the program offered")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PROGRAMCOMPLETIONNEWSITUATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _programcompletionnewsituation
        End Get
    End Property

End Class
