Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture GeneralComments Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "e31f95fd-cae4-4eb3-bd59-fc43c0491cec", "af0fb3b2-ce40-42b9-8356-6eee03250946", "ChildDeparture")> _
Partial Public Class [ChildDepartureGeneralCommentsEditDataFormUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _generalcomments As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _generalcomments = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("e31f95fd-cae4-4eb3-bd59-fc43c0491cec")
        MyBase.DataFormInstanceId = New Guid("af0fb3b2-ce40-42b9-8356-6eee03250946")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureGeneralCommentsEditDataForm.html"

        '
        '_generalcomments
        '
        _generalcomments.Name = DepartureFieldNames.GENERALCOMMENTS.ToString()
        _generalcomments.Caption = "Summarize the project's overall impact on the child's life and provide any additional comments"
        _generalcomments.MaxLength = 1000
        _generalcomments.MultiLine = True
        _generalcomments.AllowZoom = True
        Me.Fields.Add(_generalcomments)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Summarize the project's overall impact on the child's life and provide any additional comments
    ''' </summary>
    <System.ComponentModel.Description("Summarize the project's overall impact on the child's life and provide any additional comments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [GENERALCOMMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _generalcomments
        End Get
    End Property

End Class
