Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture Spiritual and Physical Impact Tab View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "cf448a84-d3a1-46bd-9cf9-dff5e73f3fd2", "c63f6464-8ea0-431a-9251-00d83de4c355", "ChildDeparture")> _
Partial Public Class [ChildDepartureSpiritualAndPhysicalImpactTabViewFormUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the ISCHILDCHRISTIANCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum ISCHILDCHRISTIANCODES As Integer
        [No] = 0
        [Yes] = 1
        [Unknown] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the DIDBECOMECHRISTIANCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum DIDBECOMECHRISTIANCODES As Integer
        [No] = 0
        [Yes] = 1
        [Unknown] = 2
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _ischildchristian As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childchristiancomments As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _didbecomechristian As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _showschristianknowledge As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _participateschristianactivities As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _showschristianevidence As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _ownsbiblematerials As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _childchristianexperience As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _healthconditions As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _ischildchristian = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childchristiancomments = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _didbecomechristian = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _showschristianknowledge = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _participateschristianactivities = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _showschristianevidence = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _ownsbiblematerials = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _childchristianexperience = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _healthconditions = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("cf448a84-d3a1-46bd-9cf9-dff5e73f3fd2")
        MyBase.DataFormInstanceId = New Guid("c63f6464-8ea0-431a-9251-00d83de4c355")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureSpiritualAndPhysicalImpactTabViewForm.html"

        '
        '_ischildchristian
        '
        _ischildchristian.Name = "ISCHILDCHRISTIAN"
        _ischildchristian.Caption = "Child is a Christian"
        _ischildchristian.DBReadOnly = True
        '_ischildchristian.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[No], .Translation = "No"})
        '_ischildchristian.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[Yes], .Translation = "Yes"})
        '_ischildchristian.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ISCHILDCHRISTIANCODES)) With {.Value = ISCHILDCHRISTIANCODES.[Unknown], .Translation = "Unknown"})
        Me.Fields.Add(_ischildchristian)
        '
        '_childchristiancomments
        '
        _childchristiancomments.Name = "CHILDCHRISTIANCOMMENTS"
        _childchristiancomments.Caption = "Comments"
        _childchristiancomments.DBReadOnly = True
        _childchristiancomments.MaxLength = 50
        Me.Fields.Add(_childchristiancomments)
        '
        '_didbecomechristiancode
        '
        _didbecomechristian.Name = "DIDBECOMECHRISTIAN"
        _didbecomechristian.Caption = "Child became a Christian while in the sponsorship program"
        _didbecomechristian.DBReadOnly = True
        '_didbecomechristian.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[No], .Translation = "No"})
        '_didbecomechristian.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[Yes], .Translation = "Yes"})
        '_didbecomechristian.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of DIDBECOMECHRISTIANCODES)) With {.Value = DIDBECOMECHRISTIANCODES.[Unknown], .Translation = "Unknown"})
        Me.Fields.Add(_didbecomechristian)
        '
        '_showschristianknowledge
        '
        _showschristianknowledge.Name = "SHOWSCHRISTIANKNOWLEDGE"
        _showschristianknowledge.Caption = "Child shows some knowledge of the Christian faith"
        _showschristianknowledge.DBReadOnly = True
        Me.Fields.Add(_showschristianknowledge)
        '
        '_participateschristianactivities
        '
        _participateschristianactivities.Name = "PARTICIPATESCHRISTIANACTIVITIES"
        _participateschristianactivities.Caption = "Child sometimes participates in Christian activities, but does not lead those activities"
        _participateschristianactivities.DBReadOnly = True
        Me.Fields.Add(_participateschristianactivities)
        '
        '_showschristianevidence
        '
        _showschristianevidence.Name = "SHOWSCHRISTIANEVIDENCE"
        _showschristianevidence.Caption = "Child shows some evidence of Christian faith and behavior"
        _showschristianevidence.DBReadOnly = True
        Me.Fields.Add(_showschristianevidence)
        '
        '_ownsbiblematerials
        '
        _ownsbiblematerials.Name = "OWNSBIBLEMATERIALS"
        _ownsbiblematerials.Caption = "Child has Scripture materials"
        _ownsbiblematerials.DBReadOnly = True
        Me.Fields.Add(_ownsbiblematerials)
        '
        '_childchristianexperience
        '
        _childchristianexperience.Name = "CHILDCHRISTIANEXPERIENCE"
        _childchristianexperience.Caption = "Provide a detailed explanation of the child's Christian experience"
        _childchristianexperience.DBReadOnly = True
        _childchristianexperience.MaxLength = 1000
        _childchristianexperience.MultiLine = True
        Me.Fields.Add(_childchristianexperience)
        '
        '_healthconditions
        '
        _healthconditions.Name = "HEALTHCONDITIONS"
        _healthconditions.Caption = "Note any illnesses the child had during their participaton in the program as well as what the child's current health is"
        _healthconditions.DBReadOnly = True
        _healthconditions.MaxLength = 1000
        _healthconditions.MultiLine = True
        _healthconditions.AllowZoom = True
        Me.Fields.Add(_healthconditions)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Child is a Christian
    ''' </summary>
    <System.ComponentModel.Description("Child is a Christian")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ISCHILDCHRISTIAN]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _ischildchristian
        End Get
    End Property

    ''' <summary>
    ''' Comments
    ''' </summary>
    <System.ComponentModel.Description("Comments")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCHRISTIANCOMMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childchristiancomments
        End Get
    End Property

    ''' <summary>
    ''' Child became a Christian while in the sponsorship program
    ''' </summary>
    <System.ComponentModel.Description("Child became a Christian while in the sponsorship program")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DIDBECOMECHRISTIAN]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _didbecomechristian
        End Get
    End Property

    ''' <summary>
    ''' Child shows some knowledge of the Christian faith
    ''' </summary>
    <System.ComponentModel.Description("Child shows some knowledge of the Christian faith")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SHOWSCHRISTIANKNOWLEDGE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showschristianknowledge
        End Get
    End Property

    ''' <summary>
    ''' Child sometimes participates in Christian activities, but does not lead those activities
    ''' </summary>
    <System.ComponentModel.Description("Child sometimes participates in Christian activities, but does not lead those activities")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [PARTICIPATESCHRISTIANACTIVITIES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _participateschristianactivities
        End Get
    End Property

    ''' <summary>
    ''' Child shows some evidence of Christian faith and behavior
    ''' </summary>
    <System.ComponentModel.Description("Child shows some evidence of Christian faith and behavior")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [SHOWSCHRISTIANEVIDENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showschristianevidence
        End Get
    End Property

    ''' <summary>
    ''' Child has Scripture materials
    ''' </summary>
    <System.ComponentModel.Description("Child has Scripture materials")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [OWNSBIBLEMATERIALS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _ownsbiblematerials
        End Get
    End Property

    ''' <summary>
    ''' Provide a detailed explanation of the child's Christian experience
    ''' </summary>
    <System.ComponentModel.Description("Provide a detailed explanation of the child's Christian experience")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDCHRISTIANEXPERIENCE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childchristianexperience
        End Get
    End Property

    ''' <summary>
    ''' Note any illnesses the child had during their participaton in the program as well as what the child's current health is
    ''' </summary>
    <System.ComponentModel.Description("Note any illnesses the child had during their participaton in the program as well as what the child's current health is")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [HEALTHCONDITIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _healthconditions
        End Get
    End Property

End Class
