Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.91.1535.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ChildDeparture Summary View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "5af633f7-bcb2-46a4-8b96-48d7722d0e10", "b5ebbe6a-9f57-4dcf-b9ea-6ddc173aa479", "ChildDeparture")> _
Partial Public Class [ChildDepartureSummaryViewFormUIModel]
    Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the RECEIVEDFAREWELLLETTERCODE property
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Enum RECEIVEDFAREWELLLETTERCODES As Integer
        [No] = 0
        [Yes] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _childname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _departuretype As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _nodepartureform As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _receivedfarewellletter As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _administrativecode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _administrativeexplanation As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _dateformcompleted As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _formcompletedby As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _dateofdeparture As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _dateprocessed As Global.Blackbaud.AppFx.UIModeling.Core.DateField

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public Sub New()
        MyBase.New()

        _childname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _departuretype = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _nodepartureform = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _receivedfarewellletter = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _administrativecode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _administrativeexplanation = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _dateformcompleted = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _formcompletedby = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _dateofdeparture = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _dateprocessed = New Global.Blackbaud.AppFx.UIModeling.Core.DateField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("5af633f7-bcb2-46a4-8b96-48d7722d0e10")
        MyBase.DataFormInstanceId = New Guid("b5ebbe6a-9f57-4dcf-b9ea-6ddc173aa479")
        MyBase.RecordType = "ChildDeparture"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildDepartureSummaryViewForm.html"

        '
        '_childname
        '
        _childname.Name = "CHILDNAME"
        _childname.Caption = "Child Name"
        _childname.DBReadOnly = True
        _childname.MaxLength = 220
        Me.Fields.Add(_childname)
        '
        '_nodepartureform
        '
        _nodepartureform.Name = DepartureFieldNames.NODEPARTUREFORM.ToString()
        _nodepartureform.Caption = "No Departure Form"
        _nodepartureform.DBReadOnly = True
        Me.Fields.Add(_nodepartureform)
        '
        '_receivedfarewelllettercode
        '
        _receivedfarewellletter.Name = "RECEIVEDFAREWELLLETTER"
        _receivedfarewellletter.Caption = "Received farewell letter"
        _receivedfarewellletter.DBReadOnly = True
        '_receivedfarewellletter.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES)) With {.Value = RECEIVEDFAREWELLLETTERCODES.[No], .Translation = "No"})
        '_receivedfarewellletter.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RECEIVEDFAREWELLLETTERCODES)) With {.Value = RECEIVEDFAREWELLLETTERCODES.[Yes], .Translation = "Yes"})
        Me.Fields.Add(_receivedfarewellletter)
        '
        '_departuretype
        '
        _departuretype.Name = "DEPARTURETYPE"
        _departuretype.Caption = "Type of departure"
        _departuretype.DBReadOnly = True
        _departuretype.MaxLength = 15
        Me.Fields.Add(_departuretype)
        '
        '_administrativecode
        '
        _administrativecode.Name = "ADMINISTRATIVECODE"
        _administrativecode.Caption = "Administrative"
        _administrativecode.DBReadOnly = True
        _administrativecode.MaxLength = 100
        Me.Fields.Add(_administrativecode)
        '
        '_administrativeexplanation
        '
        _administrativeexplanation.Name = DepartureFieldNames.ADMINISTRATIVEEXPLANATION.ToString()
        _administrativeexplanation.Caption = "Explanation"
        _administrativeexplanation.DBReadOnly = True
        _administrativeexplanation.MaxLength = 50
        Me.Fields.Add(_administrativeexplanation)
        '
        '_dateformcompleted
        '
        _dateformcompleted.Name = DepartureFieldNames.DATEFORMCOMPLETED.ToString()
        _dateformcompleted.Caption = "Form Completed Date"
        _dateformcompleted.DBReadOnly = True
        Me.Fields.Add(_dateformcompleted)
        '
        '_formcompletedby
        '
        _formcompletedby.Name = DepartureFieldNames.FORMCOMPLETEDBY.ToString()
        _formcompletedby.Caption = "Form Completed By"
        _formcompletedby.DBReadOnly = True
        _formcompletedby.MaxLength = 50
        Me.Fields.Add(_formcompletedby)
        '
        '_dateofdeparture
        '
        _dateofdeparture.Name = DepartureFieldNames.DATEOFDEPARTURE.ToString()
        _dateofdeparture.Caption = "Date of the departure or program completion"
        _dateofdeparture.DBReadOnly = True
        Me.Fields.Add(_dateofdeparture)
        '
        '_dateprocessed
        '
        _dateprocessed.Name = DepartureFieldNames.DATEPROCESSED.ToString()
        _dateprocessed.Caption = "Date processed"
        _dateprocessed.DBReadOnly = True
        Me.Fields.Add(_dateprocessed)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Child Name
    ''' </summary>
    <System.ComponentModel.Description("Child Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [CHILDNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childname
        End Get
    End Property
    '''
    ''' <summary>
    ''' Type of departure
    ''' </summary>
    <System.ComponentModel.Description("Type of departure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DEPARTURETYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _departuretype
        End Get
    End Property
    ''' <summary>
    ''' No Departure Form
    ''' </summary>
    <System.ComponentModel.Description("No Departure Form")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [NODEPARTUREFORM]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _nodepartureform
        End Get
    End Property

    ''' <summary>
    ''' Received farewell letter
    ''' </summary>
    <System.ComponentModel.Description("Received farewell letter")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [RECEIVEDFAREWELLLETTER]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _receivedfarewellletter
        End Get
    End Property

    ''' <summary>
    ''' Administrative
    ''' </summary>
    <System.ComponentModel.Description("Administrative")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADMINISTRATIVECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _administrativecode
        End Get
    End Property

    ''' <summary>
    ''' Explanation
    ''' </summary>
    <System.ComponentModel.Description("Explanation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [ADMINISTRATIVEEXPLANATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _administrativeexplanation
        End Get
    End Property

    ''' <summary>
    ''' Form Completed Date
    ''' </summary>
    <System.ComponentModel.Description("Form Completed Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEFORMCOMPLETED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateformcompleted
        End Get
    End Property

    ''' <summary>
    ''' Form Completed By
    ''' </summary>
    <System.ComponentModel.Description("Form Completed By")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [FORMCOMPLETEDBY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _formcompletedby
        End Get
    End Property

    ''' <summary>
    ''' Date of the departure or program completion
    ''' </summary>
    <System.ComponentModel.Description("Date of the departure or program completion")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEOFDEPARTURE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateofdeparture
        End Get
    End Property

    ''' <summary>
    ''' Date processed
    ''' </summary>
    <System.ComponentModel.Description("Date processed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.91.1535.0")> _
    Public ReadOnly Property [DATEPROCESSED]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _dateprocessed
        End Get
    End Property

End Class
